package com.emi.wms.bean;

import java.io.Serializable;
import java.sql.Timestamp;
import java.util.Date;

import com.emi.sys.core.annotation.EmiColumn;
import com.emi.sys.core.annotation.EmiTable;

@EmiTable(name="AA_GoodsAllocation")
public class AaGoodsallocation implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = -1963123883264683163L;
	@EmiColumn(increment=true,name="pk")
    private Integer pk;
	@EmiColumn(ID=true,name="gid")
    private String gid;
	@EmiColumn(name="notes")
    private String notes;//备注
	@EmiColumn(name="code")
    private String code;//编码
	@EmiColumn(name="name")
    private String name;//名称
	@EmiColumn(name="whuid")
    private String whuid;//所属仓库uid
	
	private String whName;//所属仓库名称
	private String whcode;//所属仓库编码
	
    private Integer showorder;//显示顺序
    private Timestamp begintimes;
    private Timestamp endtimes;
    
    @EmiColumn(name="allocationbarcode")
    private String allocationbarcode;//货位条码
    @EmiColumn(name="istemp")
    private Integer istemp;//是否临时货位
    @EmiColumn(name="posgrade")
    private Integer posgrade;//货位等级
    @EmiColumn(name="posend")
    private Integer posend;//是否末级
    
	@EmiColumn(name="orggid")
    private String orggid;//所属组织UId
	@EmiColumn(name="sobgid")
	private String sobgid;//帐套编码
	@EmiColumn(name="isdel")
	private Integer isdel;//是否删除
	
	
	
	
    public Integer getIsdel() {
		return isdel;
	}

	public void setIsdel(Integer isdel) {
		this.isdel = isdel;
	}

	public String getWhName() {
		return whName;
	}

	public void setWhName(String whName) {
		this.whName = whName;
	}

	public String getOrggid() {
		return orggid;
	}

	public void setOrggid(String orggid) {
		this.orggid = orggid;
	}

	public String getSobgid() {
		return sobgid;
	}

	public void setSobgid(String sobgid) {
		this.sobgid = sobgid;
	}

	public Integer getPk() {
        return pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.AA_GoodsAllocation.pk
     *
     * @param pk the value for dbo.AA_GoodsAllocation.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setPk(Integer pk) {
        this.pk = pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.AA_GoodsAllocation.gid
     *
     * @return the value of dbo.AA_GoodsAllocation.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.AA_GoodsAllocation.gid
     *
     * @param gid the value for dbo.AA_GoodsAllocation.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setGid(String gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.AA_GoodsAllocation.notes
     *
     * @return the value of dbo.AA_GoodsAllocation.notes
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.AA_GoodsAllocation.notes
     *
     * @param notes the value for dbo.AA_GoodsAllocation.notes
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setNotes(String notes) {
        this.notes = notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.AA_GoodsAllocation.code
     *
     * @return the value of dbo.AA_GoodsAllocation.code
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.AA_GoodsAllocation.code
     *
     * @param code the value for dbo.AA_GoodsAllocation.code
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.AA_GoodsAllocation.name
     *
     * @return the value of dbo.AA_GoodsAllocation.name
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.AA_GoodsAllocation.name
     *
     * @param name the value for dbo.AA_GoodsAllocation.name
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.AA_GoodsAllocation.whUid
     *
     * @return the value of dbo.AA_GoodsAllocation.whUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getWhuid() {
        return whuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.AA_GoodsAllocation.whUid
     *
     * @param whuid the value for dbo.AA_GoodsAllocation.whUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setWhuid(String whuid) {
        this.whuid = whuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.AA_GoodsAllocation.showOrder
     *
     * @return the value of dbo.AA_GoodsAllocation.showOrder
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Integer getShoworder() {
        return showorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.AA_GoodsAllocation.showOrder
     *
     * @param showorder the value for dbo.AA_GoodsAllocation.showOrder
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setShoworder(Integer showorder) {
        this.showorder = showorder;
    }

//    public Date getBegintimes() {
//        return begintimes;
//    }
//
//    public void setBegintimes(Date begintimes) {
//        this.begintimes = begintimes;
//    }
//
//
//    public Date getEndtimes() {
//        return endtimes;
//    }
//
//
//    public void setEndtimes(Date endtimes) {
//        this.endtimes = endtimes;
//    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.AA_GoodsAllocation.allocationBarCode
     *
     * @return the value of dbo.AA_GoodsAllocation.allocationBarCode
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getAllocationbarcode() {
        return allocationbarcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.AA_GoodsAllocation.allocationBarCode
     *
     * @param allocationbarcode the value for dbo.AA_GoodsAllocation.allocationBarCode
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setAllocationbarcode(String allocationbarcode) {
        this.allocationbarcode = allocationbarcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.AA_GoodsAllocation.isTemp
     *
     * @return the value of dbo.AA_GoodsAllocation.isTemp
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Integer getIstemp() {
        return istemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.AA_GoodsAllocation.isTemp
     *
     * @param istemp the value for dbo.AA_GoodsAllocation.isTemp
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setIstemp(Integer istemp) {
        this.istemp = istemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.AA_GoodsAllocation.posGrade
     *
     * @return the value of dbo.AA_GoodsAllocation.posGrade
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Integer getPosgrade() {
        return posgrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.AA_GoodsAllocation.posGrade
     *
     * @param posgrade the value for dbo.AA_GoodsAllocation.posGrade
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setPosgrade(Integer posgrade) {
        this.posgrade = posgrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.AA_GoodsAllocation.posEnd
     *
     * @return the value of dbo.AA_GoodsAllocation.posEnd
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Integer getPosend() {
        return posend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.AA_GoodsAllocation.posEnd
     *
     * @param posend the value for dbo.AA_GoodsAllocation.posEnd
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setPosend(Integer posend) {
        this.posend = posend;
    }

	public String getWhcode() {
		return whcode;
	}

	public void setWhcode(String whcode) {
		this.whcode = whcode;
	}


}