package com.emi.wms.bean;

import java.io.Serializable;
import java.util.Date;

import com.emi.sys.core.annotation.EmiColumn;
import com.emi.sys.core.annotation.EmiTable;
@EmiTable(name="AA_Provider_Customer")
public class AaProviderCustomer implements Serializable {


	private static final long serialVersionUID = 3163472525016607754L;


	@EmiColumn(name="pk" ,increment=true)
    private Integer pk;//客商ID


	@EmiColumn(name = "gid", ID = true)
    private String gid;//客商Uid


	@EmiColumn(name="pcCode" )
    private String pccode;//客商编号


	@EmiColumn(name="pcName" )
    private String pcname;//客商名称


	@EmiColumn(name="addr" )
    private String addr;//客商地址


	@EmiColumn(name="beginTimes" )
    private Date begintimes;//启用时间


	@EmiColumn(name="endTimes" )
    private Date endtimes;//停用时间


	@EmiColumn(name="soulationId" )
    private String soulationid;//属性方案Id


	@EmiColumn(name="sobId" )
    private String sobid;//帐套ID

	@EmiColumn(name="orgId" )
    private String orgid;//组织ID
	
	@EmiColumn(name="customerId" )
    private String customerId;//客户ID
	
	@EmiColumn(name="providerId" )
    private String providerId;//供应商ID
	
	@EmiColumn(name="isDel" )
    private String isDel;//是否删除

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.AA_Provider_Customer.pk
     *
     * @return the value of dbo.AA_Provider_Customer.pk
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public Integer getPk() {
        return pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.AA_Provider_Customer.pk
     *
     * @param pk the value for dbo.AA_Provider_Customer.pk
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setPk(Integer pk) {
        this.pk = pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.AA_Provider_Customer.gid
     *
     * @return the value of dbo.AA_Provider_Customer.gid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public String getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.AA_Provider_Customer.gid
     *
     * @param gid the value for dbo.AA_Provider_Customer.gid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setGid(String gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.AA_Provider_Customer.pcCode
     *
     * @return the value of dbo.AA_Provider_Customer.pcCode
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public String getPccode() {
        return pccode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.AA_Provider_Customer.pcCode
     *
     * @param pccode the value for dbo.AA_Provider_Customer.pcCode
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setPccode(String pccode) {
        this.pccode = pccode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.AA_Provider_Customer.pcName
     *
     * @return the value of dbo.AA_Provider_Customer.pcName
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public String getPcname() {
        return pcname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.AA_Provider_Customer.pcName
     *
     * @param pcname the value for dbo.AA_Provider_Customer.pcName
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setPcname(String pcname) {
        this.pcname = pcname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.AA_Provider_Customer.addr
     *
     * @return the value of dbo.AA_Provider_Customer.addr
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.AA_Provider_Customer.addr
     *
     * @param addr the value for dbo.AA_Provider_Customer.addr
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setAddr(String addr) {
        this.addr = addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.AA_Provider_Customer.beginTimes
     *
     * @return the value of dbo.AA_Provider_Customer.beginTimes
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public Date getBegintimes() {
        return begintimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.AA_Provider_Customer.beginTimes
     *
     * @param begintimes the value for dbo.AA_Provider_Customer.beginTimes
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setBegintimes(Date begintimes) {
        this.begintimes = begintimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.AA_Provider_Customer.endTimes
     *
     * @return the value of dbo.AA_Provider_Customer.endTimes
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public Date getEndtimes() {
        return endtimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.AA_Provider_Customer.endTimes
     *
     * @param endtimes the value for dbo.AA_Provider_Customer.endTimes
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setEndtimes(Date endtimes) {
        this.endtimes = endtimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.AA_Provider_Customer.soulationId
     *
     * @return the value of dbo.AA_Provider_Customer.soulationId
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public String getSoulationid() {
        return soulationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.AA_Provider_Customer.soulationId
     *
     * @param soulationid the value for dbo.AA_Provider_Customer.soulationId
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setSoulationid(String soulationid) {
        this.soulationid = soulationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.AA_Provider_Customer.sobId
     *
     * @return the value of dbo.AA_Provider_Customer.sobId
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public String getSobid() {
        return sobid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.AA_Provider_Customer.sobId
     *
     * @param sobid the value for dbo.AA_Provider_Customer.sobId
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setSobid(String sobid) {
        this.sobid = sobid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.AA_Provider_Customer.orgId
     *
     * @return the value of dbo.AA_Provider_Customer.orgId
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public String getOrgid() {
        return orgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.AA_Provider_Customer.orgId
     *
     * @param orgid the value for dbo.AA_Provider_Customer.orgId
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setOrgid(String orgid) {
        this.orgid = orgid;
    }

	public String getCustomerId() {
		return customerId;
	}

	public void setCustomerId(String customerId) {
		this.customerId = customerId;
	}

	public String getProviderId() {
		return providerId;
	}

	public void setProviderId(String providerId) {
		this.providerId = providerId;
	}

	public String getIsDel() {
		return isDel;
	}

	public void setIsDel(String isDel) {
		this.isDel = isDel;
	}

    
}