package com.emi.wms.bean;

import java.io.Serializable;
import java.sql.Timestamp;
import java.util.Date;

import com.emi.sys.core.annotation.EmiColumn;
import com.emi.sys.core.annotation.EmiTable;

@EmiTable(name="AA_WareHouse")
public class AaWarehouse implements Serializable {

	private static final long serialVersionUID = 6130392809873713887L;
	@EmiColumn(increment=true,name="pk")
    private Integer pk;
	@EmiColumn(ID=true,name="gid")
    private String gid;//仓库UID
	@EmiColumn(name="notes")
    private String notes;//备注
	@EmiColumn(name="whcode")
    private String whcode;//仓库编码
	@EmiColumn(name="whname")
    private String whname;//仓库名称
	@EmiColumn(name="whaddr")
    private String whaddr;//仓库地址
	@EmiColumn(name="whtel")
    private String whtel;//仓库电话
	@EmiColumn(name="linkman")
    private String linkman;//仓库联系人
	@EmiColumn(name="longitude")
    private Double longitude;//仓库经度
	@EmiColumn(name="latitude")
    private Double latitude;//仓库纬度
	@EmiColumn(name="orggid")
    private String orggid;//所属组织UId
	@EmiColumn(name="sobgid")
	private String sobgid;//帐套编码
    private Timestamp begintimes;//生效时间
    private Timestamp endtimes;//失效时间
    @EmiColumn(name="barcode")
    private String barcode;//仓库条码
    @EmiColumn(name="whpos")
    private Integer whpos;//是否货位管理
    @EmiColumn(name="isDel")
    private Integer isDel;//是否删除
    
    @EmiColumn(name="bproxyWh")
    private Integer bproxyWh;//是否删除
    
    
    
    public Integer getBproxyWh() {
		return bproxyWh;
	}

	public void setBproxyWh(Integer bproxyWh) {
		this.bproxyWh = bproxyWh;
	}

	public Integer getIsDel() {
		return isDel;
	}

	public void setIsDel(Integer isDel) {
		this.isDel = isDel;
	}

	public Double getLongitude() {
		return longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	public Double getLatitude() {
		return latitude;
	}

	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

	public String getOrggid() {
		return orggid;
	}

	public void setOrggid(String orggid) {
		this.orggid = orggid;
	}

	public void setBegintimes(Timestamp begintimes) {
		this.begintimes = begintimes;
	}

	public void setEndtimes(Timestamp endtimes) {
		this.endtimes = endtimes;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.AA_WareHouse.soulationId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String soulationid;



    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.AA_WareHouse.flag
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Integer flag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.AA_WareHouse.pk
     *
     * @return the value of dbo.AA_WareHouse.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Integer getPk() {
        return pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.AA_WareHouse.pk
     *
     * @param pk the value for dbo.AA_WareHouse.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setPk(Integer pk) {
        this.pk = pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.AA_WareHouse.gid
     *
     * @return the value of dbo.AA_WareHouse.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.AA_WareHouse.gid
     *
     * @param gid the value for dbo.AA_WareHouse.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setGid(String gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.AA_WareHouse.notes
     *
     * @return the value of dbo.AA_WareHouse.notes
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.AA_WareHouse.notes
     *
     * @param notes the value for dbo.AA_WareHouse.notes
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setNotes(String notes) {
        this.notes = notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.AA_WareHouse.whCode
     *
     * @return the value of dbo.AA_WareHouse.whCode
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getWhcode() {
        return whcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.AA_WareHouse.whCode
     *
     * @param whcode the value for dbo.AA_WareHouse.whCode
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setWhcode(String whcode) {
        this.whcode = whcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.AA_WareHouse.whName
     *
     * @return the value of dbo.AA_WareHouse.whName
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getWhname() {
        return whname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.AA_WareHouse.whName
     *
     * @param whname the value for dbo.AA_WareHouse.whName
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setWhname(String whname) {
        this.whname = whname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.AA_WareHouse.whAddr
     *
     * @return the value of dbo.AA_WareHouse.whAddr
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getWhaddr() {
        return whaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.AA_WareHouse.whAddr
     *
     * @param whaddr the value for dbo.AA_WareHouse.whAddr
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setWhaddr(String whaddr) {
        this.whaddr = whaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.AA_WareHouse.whTel
     *
     * @return the value of dbo.AA_WareHouse.whTel
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getWhtel() {
        return whtel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.AA_WareHouse.whTel
     *
     * @param whtel the value for dbo.AA_WareHouse.whTel
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setWhtel(String whtel) {
        this.whtel = whtel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.AA_WareHouse.linkMan
     *
     * @return the value of dbo.AA_WareHouse.linkMan
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getLinkman() {
        return linkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.AA_WareHouse.linkMan
     *
     * @param linkman the value for dbo.AA_WareHouse.linkMan
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setLinkman(String linkman) {
        this.linkman = linkman;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.AA_WareHouse.beginTimes
     *
     * @return the value of dbo.AA_WareHouse.beginTimes
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Date getBegintimes() {
        return begintimes;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.AA_WareHouse.endTimes
     *
     * @return the value of dbo.AA_WareHouse.endTimes
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Date getEndtimes() {
        return endtimes;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.AA_WareHouse.barCode
     *
     * @return the value of dbo.AA_WareHouse.barCode
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getBarcode() {
        return barcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.AA_WareHouse.barCode
     *
     * @param barcode the value for dbo.AA_WareHouse.barCode
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setBarcode(String barcode) {
        this.barcode = barcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.AA_WareHouse.whPos
     *
     * @return the value of dbo.AA_WareHouse.whPos
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Integer getWhpos() {
        return whpos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.AA_WareHouse.whPos
     *
     * @param whpos the value for dbo.AA_WareHouse.whPos
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setWhpos(Integer whpos) {
        this.whpos = whpos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.AA_WareHouse.soulationId
     *
     * @return the value of dbo.AA_WareHouse.soulationId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getSoulationid() {
        return soulationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.AA_WareHouse.soulationId
     *
     * @param soulationid the value for dbo.AA_WareHouse.soulationId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setSoulationid(String soulationid) {
        this.soulationid = soulationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.AA_WareHouse.sobGid
     *
     * @return the value of dbo.AA_WareHouse.sobGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getSobgid() {
        return sobgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.AA_WareHouse.sobGid
     *
     * @param sobgid the value for dbo.AA_WareHouse.sobGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setSobgid(String sobgid) {
        this.sobgid = sobgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.AA_WareHouse.flag
     *
     * @return the value of dbo.AA_WareHouse.flag
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.AA_WareHouse.flag
     *
     * @param flag the value for dbo.AA_WareHouse.flag
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }
}