package com.emi.wms.bean;

public class Constant {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.constant.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Integer pk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.constant.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String gid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.constant.constantName
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String constantname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.constant.pk
     *
     * @return the value of dbo.constant.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Integer getPk() {
        return pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.constant.pk
     *
     * @param pk the value for dbo.constant.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setPk(Integer pk) {
        this.pk = pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.constant.gid
     *
     * @return the value of dbo.constant.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.constant.gid
     *
     * @param gid the value for dbo.constant.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setGid(String gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.constant.constantName
     *
     * @return the value of dbo.constant.constantName
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getConstantname() {
        return constantname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.constant.constantName
     *
     * @param constantname the value for dbo.constant.constantName
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setConstantname(String constantname) {
        this.constantname = constantname;
    }
}