package com.emi.wms.bean;

public class Equipmentperson {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.equipmentPerson.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Integer pk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.equipmentPerson.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String gid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.equipmentPerson.equipmentId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String equipmentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.equipmentPerson.personId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String personid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.equipmentPerson.pk
     *
     * @return the value of dbo.equipmentPerson.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Integer getPk() {
        return pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.equipmentPerson.pk
     *
     * @param pk the value for dbo.equipmentPerson.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setPk(Integer pk) {
        this.pk = pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.equipmentPerson.gid
     *
     * @return the value of dbo.equipmentPerson.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.equipmentPerson.gid
     *
     * @param gid the value for dbo.equipmentPerson.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setGid(String gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.equipmentPerson.equipmentId
     *
     * @return the value of dbo.equipmentPerson.equipmentId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getEquipmentid() {
        return equipmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.equipmentPerson.equipmentId
     *
     * @param equipmentid the value for dbo.equipmentPerson.equipmentId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setEquipmentid(String equipmentid) {
        this.equipmentid = equipmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.equipmentPerson.personId
     *
     * @return the value of dbo.equipmentPerson.personId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getPersonid() {
        return personid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.equipmentPerson.personId
     *
     * @param personid the value for dbo.equipmentPerson.personId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setPersonid(String personid) {
        this.personid = personid;
    }
}