package com.emi.wms.bean;

import java.util.Date;

public class FlowHistorymain {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_HistoryMain.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Integer pk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_HistoryMain.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String gid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_HistoryMain.status
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_HistoryMain.ownerId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String ownerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_HistoryMain.createTime
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_HistoryMain.completeTime
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Date completetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_HistoryMain.deleteTime
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Date deletetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_HistoryMain.titleValue
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String titlevalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_HistoryMain.sobGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String sobgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_HistoryMain.orgGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String orggid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_HistoryMain.pk
     *
     * @return the value of dbo.FLOW_HistoryMain.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Integer getPk() {
        return pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_HistoryMain.pk
     *
     * @param pk the value for dbo.FLOW_HistoryMain.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setPk(Integer pk) {
        this.pk = pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_HistoryMain.gid
     *
     * @return the value of dbo.FLOW_HistoryMain.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_HistoryMain.gid
     *
     * @param gid the value for dbo.FLOW_HistoryMain.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setGid(String gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_HistoryMain.status
     *
     * @return the value of dbo.FLOW_HistoryMain.status
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_HistoryMain.status
     *
     * @param status the value for dbo.FLOW_HistoryMain.status
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_HistoryMain.ownerId
     *
     * @return the value of dbo.FLOW_HistoryMain.ownerId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getOwnerid() {
        return ownerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_HistoryMain.ownerId
     *
     * @param ownerid the value for dbo.FLOW_HistoryMain.ownerId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setOwnerid(String ownerid) {
        this.ownerid = ownerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_HistoryMain.createTime
     *
     * @return the value of dbo.FLOW_HistoryMain.createTime
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_HistoryMain.createTime
     *
     * @param createtime the value for dbo.FLOW_HistoryMain.createTime
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_HistoryMain.completeTime
     *
     * @return the value of dbo.FLOW_HistoryMain.completeTime
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Date getCompletetime() {
        return completetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_HistoryMain.completeTime
     *
     * @param completetime the value for dbo.FLOW_HistoryMain.completeTime
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setCompletetime(Date completetime) {
        this.completetime = completetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_HistoryMain.deleteTime
     *
     * @return the value of dbo.FLOW_HistoryMain.deleteTime
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Date getDeletetime() {
        return deletetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_HistoryMain.deleteTime
     *
     * @param deletetime the value for dbo.FLOW_HistoryMain.deleteTime
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setDeletetime(Date deletetime) {
        this.deletetime = deletetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_HistoryMain.titleValue
     *
     * @return the value of dbo.FLOW_HistoryMain.titleValue
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getTitlevalue() {
        return titlevalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_HistoryMain.titleValue
     *
     * @param titlevalue the value for dbo.FLOW_HistoryMain.titleValue
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setTitlevalue(String titlevalue) {
        this.titlevalue = titlevalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_HistoryMain.sobGid
     *
     * @return the value of dbo.FLOW_HistoryMain.sobGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getSobgid() {
        return sobgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_HistoryMain.sobGid
     *
     * @param sobgid the value for dbo.FLOW_HistoryMain.sobGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setSobgid(String sobgid) {
        this.sobgid = sobgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_HistoryMain.orgGid
     *
     * @return the value of dbo.FLOW_HistoryMain.orgGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getOrggid() {
        return orggid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_HistoryMain.orgGid
     *
     * @param orggid the value for dbo.FLOW_HistoryMain.orgGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setOrggid(String orggid) {
        this.orggid = orggid;
    }
}