package com.emi.wms.bean;

import java.math.BigDecimal;
import java.util.Date;

public class FlowForm {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_Form.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Integer pk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_Form.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String gid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_Form.formName
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String formname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_Form.tableId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String tableid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_Form.childTableId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String childtableid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_Form.titleCfg
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String titlecfg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_Form.description
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_Form.createUserId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String createuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_Form.createTime
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_Form.version
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private BigDecimal version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_Form.isPageForm
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Integer ispageform;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_Form.pageUrl
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String pageurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_Form.dataFromAction
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Integer datafromaction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_Form.actionName
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String actionname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_Form.isSys
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Integer issys;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_Form.sobGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String sobgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_Form.orgGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String orggid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_Form.formHtml
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String formhtml;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_Form.scripts
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String scripts;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_Form.pk
     *
     * @return the value of dbo.FLOW_Form.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Integer getPk() {
        return pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_Form.pk
     *
     * @param pk the value for dbo.FLOW_Form.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setPk(Integer pk) {
        this.pk = pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_Form.gid
     *
     * @return the value of dbo.FLOW_Form.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_Form.gid
     *
     * @param gid the value for dbo.FLOW_Form.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setGid(String gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_Form.formName
     *
     * @return the value of dbo.FLOW_Form.formName
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getFormname() {
        return formname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_Form.formName
     *
     * @param formname the value for dbo.FLOW_Form.formName
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setFormname(String formname) {
        this.formname = formname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_Form.tableId
     *
     * @return the value of dbo.FLOW_Form.tableId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getTableid() {
        return tableid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_Form.tableId
     *
     * @param tableid the value for dbo.FLOW_Form.tableId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setTableid(String tableid) {
        this.tableid = tableid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_Form.childTableId
     *
     * @return the value of dbo.FLOW_Form.childTableId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getChildtableid() {
        return childtableid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_Form.childTableId
     *
     * @param childtableid the value for dbo.FLOW_Form.childTableId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setChildtableid(String childtableid) {
        this.childtableid = childtableid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_Form.titleCfg
     *
     * @return the value of dbo.FLOW_Form.titleCfg
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getTitlecfg() {
        return titlecfg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_Form.titleCfg
     *
     * @param titlecfg the value for dbo.FLOW_Form.titleCfg
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setTitlecfg(String titlecfg) {
        this.titlecfg = titlecfg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_Form.description
     *
     * @return the value of dbo.FLOW_Form.description
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_Form.description
     *
     * @param description the value for dbo.FLOW_Form.description
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_Form.createUserId
     *
     * @return the value of dbo.FLOW_Form.createUserId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getCreateuserid() {
        return createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_Form.createUserId
     *
     * @param createuserid the value for dbo.FLOW_Form.createUserId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setCreateuserid(String createuserid) {
        this.createuserid = createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_Form.createTime
     *
     * @return the value of dbo.FLOW_Form.createTime
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_Form.createTime
     *
     * @param createtime the value for dbo.FLOW_Form.createTime
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_Form.version
     *
     * @return the value of dbo.FLOW_Form.version
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public BigDecimal getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_Form.version
     *
     * @param version the value for dbo.FLOW_Form.version
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setVersion(BigDecimal version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_Form.isPageForm
     *
     * @return the value of dbo.FLOW_Form.isPageForm
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Integer getIspageform() {
        return ispageform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_Form.isPageForm
     *
     * @param ispageform the value for dbo.FLOW_Form.isPageForm
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setIspageform(Integer ispageform) {
        this.ispageform = ispageform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_Form.pageUrl
     *
     * @return the value of dbo.FLOW_Form.pageUrl
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getPageurl() {
        return pageurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_Form.pageUrl
     *
     * @param pageurl the value for dbo.FLOW_Form.pageUrl
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setPageurl(String pageurl) {
        this.pageurl = pageurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_Form.dataFromAction
     *
     * @return the value of dbo.FLOW_Form.dataFromAction
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Integer getDatafromaction() {
        return datafromaction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_Form.dataFromAction
     *
     * @param datafromaction the value for dbo.FLOW_Form.dataFromAction
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setDatafromaction(Integer datafromaction) {
        this.datafromaction = datafromaction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_Form.actionName
     *
     * @return the value of dbo.FLOW_Form.actionName
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getActionname() {
        return actionname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_Form.actionName
     *
     * @param actionname the value for dbo.FLOW_Form.actionName
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setActionname(String actionname) {
        this.actionname = actionname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_Form.isSys
     *
     * @return the value of dbo.FLOW_Form.isSys
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Integer getIssys() {
        return issys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_Form.isSys
     *
     * @param issys the value for dbo.FLOW_Form.isSys
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setIssys(Integer issys) {
        this.issys = issys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_Form.sobGid
     *
     * @return the value of dbo.FLOW_Form.sobGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getSobgid() {
        return sobgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_Form.sobGid
     *
     * @param sobgid the value for dbo.FLOW_Form.sobGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setSobgid(String sobgid) {
        this.sobgid = sobgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_Form.orgGid
     *
     * @return the value of dbo.FLOW_Form.orgGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getOrggid() {
        return orggid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_Form.orgGid
     *
     * @param orggid the value for dbo.FLOW_Form.orgGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setOrggid(String orggid) {
        this.orggid = orggid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_Form.formHtml
     *
     * @return the value of dbo.FLOW_Form.formHtml
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getFormhtml() {
        return formhtml;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_Form.formHtml
     *
     * @param formhtml the value for dbo.FLOW_Form.formHtml
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setFormhtml(String formhtml) {
        this.formhtml = formhtml;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_Form.scripts
     *
     * @return the value of dbo.FLOW_Form.scripts
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getScripts() {
        return scripts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_Form.scripts
     *
     * @param scripts the value for dbo.FLOW_Form.scripts
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setScripts(String scripts) {
        this.scripts = scripts;
    }
}