package com.emi.wms.bean;

public class FlowColumn {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_Column.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Integer pk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_Column.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String gid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_Column.columnName
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String columnname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_Column.columnDisplayName
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String columndisplayname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_Column.tableId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String tableid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_Column.columnType
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String columntype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_Column.columnLength
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Integer columnlength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_Column.columnDescription
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String columndescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_Column.isNull
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Integer isnull;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_Column.isShow
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Integer isshow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_Column.columnIndex
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Integer columnindex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_Column.increment
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Integer increment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_Column.isPk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Integer ispk;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_Column.pk
     *
     * @return the value of dbo.FLOW_Column.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Integer getPk() {
        return pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_Column.pk
     *
     * @param pk the value for dbo.FLOW_Column.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setPk(Integer pk) {
        this.pk = pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_Column.gid
     *
     * @return the value of dbo.FLOW_Column.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_Column.gid
     *
     * @param gid the value for dbo.FLOW_Column.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setGid(String gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_Column.columnName
     *
     * @return the value of dbo.FLOW_Column.columnName
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getColumnname() {
        return columnname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_Column.columnName
     *
     * @param columnname the value for dbo.FLOW_Column.columnName
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setColumnname(String columnname) {
        this.columnname = columnname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_Column.columnDisplayName
     *
     * @return the value of dbo.FLOW_Column.columnDisplayName
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getColumndisplayname() {
        return columndisplayname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_Column.columnDisplayName
     *
     * @param columndisplayname the value for dbo.FLOW_Column.columnDisplayName
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setColumndisplayname(String columndisplayname) {
        this.columndisplayname = columndisplayname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_Column.tableId
     *
     * @return the value of dbo.FLOW_Column.tableId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getTableid() {
        return tableid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_Column.tableId
     *
     * @param tableid the value for dbo.FLOW_Column.tableId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setTableid(String tableid) {
        this.tableid = tableid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_Column.columnType
     *
     * @return the value of dbo.FLOW_Column.columnType
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getColumntype() {
        return columntype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_Column.columnType
     *
     * @param columntype the value for dbo.FLOW_Column.columnType
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setColumntype(String columntype) {
        this.columntype = columntype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_Column.columnLength
     *
     * @return the value of dbo.FLOW_Column.columnLength
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Integer getColumnlength() {
        return columnlength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_Column.columnLength
     *
     * @param columnlength the value for dbo.FLOW_Column.columnLength
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setColumnlength(Integer columnlength) {
        this.columnlength = columnlength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_Column.columnDescription
     *
     * @return the value of dbo.FLOW_Column.columnDescription
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getColumndescription() {
        return columndescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_Column.columnDescription
     *
     * @param columndescription the value for dbo.FLOW_Column.columnDescription
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setColumndescription(String columndescription) {
        this.columndescription = columndescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_Column.isNull
     *
     * @return the value of dbo.FLOW_Column.isNull
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Integer getIsnull() {
        return isnull;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_Column.isNull
     *
     * @param isnull the value for dbo.FLOW_Column.isNull
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setIsnull(Integer isnull) {
        this.isnull = isnull;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_Column.isShow
     *
     * @return the value of dbo.FLOW_Column.isShow
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Integer getIsshow() {
        return isshow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_Column.isShow
     *
     * @param isshow the value for dbo.FLOW_Column.isShow
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setIsshow(Integer isshow) {
        this.isshow = isshow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_Column.columnIndex
     *
     * @return the value of dbo.FLOW_Column.columnIndex
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Integer getColumnindex() {
        return columnindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_Column.columnIndex
     *
     * @param columnindex the value for dbo.FLOW_Column.columnIndex
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setColumnindex(Integer columnindex) {
        this.columnindex = columnindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_Column.increment
     *
     * @return the value of dbo.FLOW_Column.increment
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Integer getIncrement() {
        return increment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_Column.increment
     *
     * @param increment the value for dbo.FLOW_Column.increment
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setIncrement(Integer increment) {
        this.increment = increment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_Column.isPk
     *
     * @return the value of dbo.FLOW_Column.isPk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Integer getIspk() {
        return ispk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_Column.isPk
     *
     * @param ispk the value for dbo.FLOW_Column.isPk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setIspk(Integer ispk) {
        this.ispk = ispk;
    }
}