package com.emi.wms.bean;

public class FlowFormdetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_FormDetail.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Integer pk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_FormDetail.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String gid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_FormDetail.formId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String formid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_FormDetail.elementName
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String elementname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_FormDetail.elementType
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String elementtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_FormDetail.columnName
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String columnname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_FormDetail.description
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_FormDetail.defaultValue
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String defaultvalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_FormDetail.defaultType
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Integer defaulttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_FormDetail.enumId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String enumid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_FormDetail.dataFormat
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String dataformat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_FormDetail.isRequired
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Integer isrequired;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_FormDetail.readOnly
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Integer readonly;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_FormDetail.listShow
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Integer listshow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_FormDetail.showIndex
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Integer showindex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_FormDetail.listenerName
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String listenername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_FormDetail.callback
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String callback;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_FormDetail.sobGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String sobgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_FormDetail.orgGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String orggid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_FormDetail.pk
     *
     * @return the value of dbo.FLOW_FormDetail.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Integer getPk() {
        return pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_FormDetail.pk
     *
     * @param pk the value for dbo.FLOW_FormDetail.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setPk(Integer pk) {
        this.pk = pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_FormDetail.gid
     *
     * @return the value of dbo.FLOW_FormDetail.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_FormDetail.gid
     *
     * @param gid the value for dbo.FLOW_FormDetail.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setGid(String gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_FormDetail.formId
     *
     * @return the value of dbo.FLOW_FormDetail.formId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getFormid() {
        return formid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_FormDetail.formId
     *
     * @param formid the value for dbo.FLOW_FormDetail.formId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setFormid(String formid) {
        this.formid = formid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_FormDetail.elementName
     *
     * @return the value of dbo.FLOW_FormDetail.elementName
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getElementname() {
        return elementname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_FormDetail.elementName
     *
     * @param elementname the value for dbo.FLOW_FormDetail.elementName
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setElementname(String elementname) {
        this.elementname = elementname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_FormDetail.elementType
     *
     * @return the value of dbo.FLOW_FormDetail.elementType
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getElementtype() {
        return elementtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_FormDetail.elementType
     *
     * @param elementtype the value for dbo.FLOW_FormDetail.elementType
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setElementtype(String elementtype) {
        this.elementtype = elementtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_FormDetail.columnName
     *
     * @return the value of dbo.FLOW_FormDetail.columnName
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getColumnname() {
        return columnname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_FormDetail.columnName
     *
     * @param columnname the value for dbo.FLOW_FormDetail.columnName
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setColumnname(String columnname) {
        this.columnname = columnname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_FormDetail.description
     *
     * @return the value of dbo.FLOW_FormDetail.description
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_FormDetail.description
     *
     * @param description the value for dbo.FLOW_FormDetail.description
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_FormDetail.defaultValue
     *
     * @return the value of dbo.FLOW_FormDetail.defaultValue
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getDefaultvalue() {
        return defaultvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_FormDetail.defaultValue
     *
     * @param defaultvalue the value for dbo.FLOW_FormDetail.defaultValue
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setDefaultvalue(String defaultvalue) {
        this.defaultvalue = defaultvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_FormDetail.defaultType
     *
     * @return the value of dbo.FLOW_FormDetail.defaultType
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Integer getDefaulttype() {
        return defaulttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_FormDetail.defaultType
     *
     * @param defaulttype the value for dbo.FLOW_FormDetail.defaultType
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setDefaulttype(Integer defaulttype) {
        this.defaulttype = defaulttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_FormDetail.enumId
     *
     * @return the value of dbo.FLOW_FormDetail.enumId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getEnumid() {
        return enumid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_FormDetail.enumId
     *
     * @param enumid the value for dbo.FLOW_FormDetail.enumId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setEnumid(String enumid) {
        this.enumid = enumid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_FormDetail.dataFormat
     *
     * @return the value of dbo.FLOW_FormDetail.dataFormat
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getDataformat() {
        return dataformat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_FormDetail.dataFormat
     *
     * @param dataformat the value for dbo.FLOW_FormDetail.dataFormat
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setDataformat(String dataformat) {
        this.dataformat = dataformat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_FormDetail.isRequired
     *
     * @return the value of dbo.FLOW_FormDetail.isRequired
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Integer getIsrequired() {
        return isrequired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_FormDetail.isRequired
     *
     * @param isrequired the value for dbo.FLOW_FormDetail.isRequired
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setIsrequired(Integer isrequired) {
        this.isrequired = isrequired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_FormDetail.readOnly
     *
     * @return the value of dbo.FLOW_FormDetail.readOnly
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Integer getReadonly() {
        return readonly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_FormDetail.readOnly
     *
     * @param readonly the value for dbo.FLOW_FormDetail.readOnly
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setReadonly(Integer readonly) {
        this.readonly = readonly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_FormDetail.listShow
     *
     * @return the value of dbo.FLOW_FormDetail.listShow
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Integer getListshow() {
        return listshow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_FormDetail.listShow
     *
     * @param listshow the value for dbo.FLOW_FormDetail.listShow
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setListshow(Integer listshow) {
        this.listshow = listshow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_FormDetail.showIndex
     *
     * @return the value of dbo.FLOW_FormDetail.showIndex
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Integer getShowindex() {
        return showindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_FormDetail.showIndex
     *
     * @param showindex the value for dbo.FLOW_FormDetail.showIndex
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setShowindex(Integer showindex) {
        this.showindex = showindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_FormDetail.listenerName
     *
     * @return the value of dbo.FLOW_FormDetail.listenerName
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getListenername() {
        return listenername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_FormDetail.listenerName
     *
     * @param listenername the value for dbo.FLOW_FormDetail.listenerName
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setListenername(String listenername) {
        this.listenername = listenername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_FormDetail.callback
     *
     * @return the value of dbo.FLOW_FormDetail.callback
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getCallback() {
        return callback;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_FormDetail.callback
     *
     * @param callback the value for dbo.FLOW_FormDetail.callback
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setCallback(String callback) {
        this.callback = callback;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_FormDetail.sobGid
     *
     * @return the value of dbo.FLOW_FormDetail.sobGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getSobgid() {
        return sobgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_FormDetail.sobGid
     *
     * @param sobgid the value for dbo.FLOW_FormDetail.sobGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setSobgid(String sobgid) {
        this.sobgid = sobgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_FormDetail.orgGid
     *
     * @return the value of dbo.FLOW_FormDetail.orgGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getOrggid() {
        return orggid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_FormDetail.orgGid
     *
     * @param orggid the value for dbo.FLOW_FormDetail.orgGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setOrggid(String orggid) {
        this.orggid = orggid;
    }
}