package com.emi.wms.bean;

import java.util.Date;

public class FlowHistory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_History.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Integer pk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_History.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String gid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_History.instanceId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String instanceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_History.flowId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String flowid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_History.formId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String formid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_History.nodeId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String nodeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_History.tableId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String tableid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_History.dataId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String dataid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_History.fromUserId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String fromuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_History.fromTime
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Date fromtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_History.acceptUserId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String acceptuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_History.acceptStatus
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Integer acceptstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_History.acceptTime
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String accepttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_History.completeStatus
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String completestatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_History.completeTime
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Date completetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_History.comment
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_History.historyMainId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String historymainid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_History.pk
     *
     * @return the value of dbo.FLOW_History.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Integer getPk() {
        return pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_History.pk
     *
     * @param pk the value for dbo.FLOW_History.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setPk(Integer pk) {
        this.pk = pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_History.gid
     *
     * @return the value of dbo.FLOW_History.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_History.gid
     *
     * @param gid the value for dbo.FLOW_History.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setGid(String gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_History.instanceId
     *
     * @return the value of dbo.FLOW_History.instanceId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getInstanceid() {
        return instanceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_History.instanceId
     *
     * @param instanceid the value for dbo.FLOW_History.instanceId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setInstanceid(String instanceid) {
        this.instanceid = instanceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_History.flowId
     *
     * @return the value of dbo.FLOW_History.flowId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getFlowid() {
        return flowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_History.flowId
     *
     * @param flowid the value for dbo.FLOW_History.flowId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setFlowid(String flowid) {
        this.flowid = flowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_History.formId
     *
     * @return the value of dbo.FLOW_History.formId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getFormid() {
        return formid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_History.formId
     *
     * @param formid the value for dbo.FLOW_History.formId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setFormid(String formid) {
        this.formid = formid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_History.nodeId
     *
     * @return the value of dbo.FLOW_History.nodeId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getNodeid() {
        return nodeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_History.nodeId
     *
     * @param nodeid the value for dbo.FLOW_History.nodeId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setNodeid(String nodeid) {
        this.nodeid = nodeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_History.tableId
     *
     * @return the value of dbo.FLOW_History.tableId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getTableid() {
        return tableid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_History.tableId
     *
     * @param tableid the value for dbo.FLOW_History.tableId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setTableid(String tableid) {
        this.tableid = tableid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_History.dataId
     *
     * @return the value of dbo.FLOW_History.dataId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getDataid() {
        return dataid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_History.dataId
     *
     * @param dataid the value for dbo.FLOW_History.dataId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setDataid(String dataid) {
        this.dataid = dataid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_History.fromUserId
     *
     * @return the value of dbo.FLOW_History.fromUserId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getFromuserid() {
        return fromuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_History.fromUserId
     *
     * @param fromuserid the value for dbo.FLOW_History.fromUserId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setFromuserid(String fromuserid) {
        this.fromuserid = fromuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_History.fromTime
     *
     * @return the value of dbo.FLOW_History.fromTime
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Date getFromtime() {
        return fromtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_History.fromTime
     *
     * @param fromtime the value for dbo.FLOW_History.fromTime
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setFromtime(Date fromtime) {
        this.fromtime = fromtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_History.acceptUserId
     *
     * @return the value of dbo.FLOW_History.acceptUserId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getAcceptuserid() {
        return acceptuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_History.acceptUserId
     *
     * @param acceptuserid the value for dbo.FLOW_History.acceptUserId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setAcceptuserid(String acceptuserid) {
        this.acceptuserid = acceptuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_History.acceptStatus
     *
     * @return the value of dbo.FLOW_History.acceptStatus
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Integer getAcceptstatus() {
        return acceptstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_History.acceptStatus
     *
     * @param acceptstatus the value for dbo.FLOW_History.acceptStatus
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setAcceptstatus(Integer acceptstatus) {
        this.acceptstatus = acceptstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_History.acceptTime
     *
     * @return the value of dbo.FLOW_History.acceptTime
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getAccepttime() {
        return accepttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_History.acceptTime
     *
     * @param accepttime the value for dbo.FLOW_History.acceptTime
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setAccepttime(String accepttime) {
        this.accepttime = accepttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_History.completeStatus
     *
     * @return the value of dbo.FLOW_History.completeStatus
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getCompletestatus() {
        return completestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_History.completeStatus
     *
     * @param completestatus the value for dbo.FLOW_History.completeStatus
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setCompletestatus(String completestatus) {
        this.completestatus = completestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_History.completeTime
     *
     * @return the value of dbo.FLOW_History.completeTime
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Date getCompletetime() {
        return completetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_History.completeTime
     *
     * @param completetime the value for dbo.FLOW_History.completeTime
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setCompletetime(Date completetime) {
        this.completetime = completetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_History.comment
     *
     * @return the value of dbo.FLOW_History.comment
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_History.comment
     *
     * @param comment the value for dbo.FLOW_History.comment
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_History.historyMainId
     *
     * @return the value of dbo.FLOW_History.historyMainId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getHistorymainid() {
        return historymainid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_History.historyMainId
     *
     * @param historymainid the value for dbo.FLOW_History.historyMainId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setHistorymainid(String historymainid) {
        this.historymainid = historymainid;
    }
}