package com.emi.wms.bean;

import java.util.Date;

public class FlowInstance {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_Instance.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Integer pk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_Instance.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String gid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_Instance.instanceId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String instanceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_Instance.flowId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String flowid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_Instance.formId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String formid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_Instance.createUserId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String createuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_Instance.createTime
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_Instance.isSys
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Integer issys;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_Instance.pageUrl
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String pageurl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_Instance.pk
     *
     * @return the value of dbo.FLOW_Instance.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Integer getPk() {
        return pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_Instance.pk
     *
     * @param pk the value for dbo.FLOW_Instance.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setPk(Integer pk) {
        this.pk = pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_Instance.gid
     *
     * @return the value of dbo.FLOW_Instance.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_Instance.gid
     *
     * @param gid the value for dbo.FLOW_Instance.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setGid(String gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_Instance.instanceId
     *
     * @return the value of dbo.FLOW_Instance.instanceId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getInstanceid() {
        return instanceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_Instance.instanceId
     *
     * @param instanceid the value for dbo.FLOW_Instance.instanceId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setInstanceid(String instanceid) {
        this.instanceid = instanceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_Instance.flowId
     *
     * @return the value of dbo.FLOW_Instance.flowId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getFlowid() {
        return flowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_Instance.flowId
     *
     * @param flowid the value for dbo.FLOW_Instance.flowId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setFlowid(String flowid) {
        this.flowid = flowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_Instance.formId
     *
     * @return the value of dbo.FLOW_Instance.formId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getFormid() {
        return formid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_Instance.formId
     *
     * @param formid the value for dbo.FLOW_Instance.formId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setFormid(String formid) {
        this.formid = formid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_Instance.createUserId
     *
     * @return the value of dbo.FLOW_Instance.createUserId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getCreateuserid() {
        return createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_Instance.createUserId
     *
     * @param createuserid the value for dbo.FLOW_Instance.createUserId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setCreateuserid(String createuserid) {
        this.createuserid = createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_Instance.createTime
     *
     * @return the value of dbo.FLOW_Instance.createTime
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_Instance.createTime
     *
     * @param createtime the value for dbo.FLOW_Instance.createTime
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_Instance.isSys
     *
     * @return the value of dbo.FLOW_Instance.isSys
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Integer getIssys() {
        return issys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_Instance.isSys
     *
     * @param issys the value for dbo.FLOW_Instance.isSys
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setIssys(Integer issys) {
        this.issys = issys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_Instance.pageUrl
     *
     * @return the value of dbo.FLOW_Instance.pageUrl
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getPageurl() {
        return pageurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_Instance.pageUrl
     *
     * @param pageurl the value for dbo.FLOW_Instance.pageUrl
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setPageurl(String pageurl) {
        this.pageurl = pageurl;
    }
}