package com.emi.wms.bean;

public class FlowCoderulevalue {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_CodeRuleValue.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Integer pk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_CodeRuleValue.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String gid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_CodeRuleValue.codeRuleId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String coderuleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_CodeRuleValue.prefixCode
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String prefixcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_CodeRuleValue.curNumber
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Integer curnumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_CodeRuleValue.pk
     *
     * @return the value of dbo.FLOW_CodeRuleValue.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Integer getPk() {
        return pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_CodeRuleValue.pk
     *
     * @param pk the value for dbo.FLOW_CodeRuleValue.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setPk(Integer pk) {
        this.pk = pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_CodeRuleValue.gid
     *
     * @return the value of dbo.FLOW_CodeRuleValue.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_CodeRuleValue.gid
     *
     * @param gid the value for dbo.FLOW_CodeRuleValue.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setGid(String gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_CodeRuleValue.codeRuleId
     *
     * @return the value of dbo.FLOW_CodeRuleValue.codeRuleId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getCoderuleid() {
        return coderuleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_CodeRuleValue.codeRuleId
     *
     * @param coderuleid the value for dbo.FLOW_CodeRuleValue.codeRuleId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setCoderuleid(String coderuleid) {
        this.coderuleid = coderuleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_CodeRuleValue.prefixCode
     *
     * @return the value of dbo.FLOW_CodeRuleValue.prefixCode
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getPrefixcode() {
        return prefixcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_CodeRuleValue.prefixCode
     *
     * @param prefixcode the value for dbo.FLOW_CodeRuleValue.prefixCode
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setPrefixcode(String prefixcode) {
        this.prefixcode = prefixcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_CodeRuleValue.curNumber
     *
     * @return the value of dbo.FLOW_CodeRuleValue.curNumber
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Integer getCurnumber() {
        return curnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_CodeRuleValue.curNumber
     *
     * @param curnumber the value for dbo.FLOW_CodeRuleValue.curNumber
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setCurnumber(Integer curnumber) {
        this.curnumber = curnumber;
    }
}