package com.emi.wms.bean;

import java.util.Date;

public class FlowEnum {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_Enum.pk
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    private Integer pk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_Enum.gid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    private String gid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_Enum.enumName
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    private String enumname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_Enum.description
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_Enum.createUserId
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    private String createuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_Enum.createTime
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_Enum.enumType
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    private Integer enumtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_Enum.tableName
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    private String tablename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_Enum.columnName
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    private String columnname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.FLOW_Enum.conditionSql
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    private String conditionsql;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_Enum.pk
     *
     * @return the value of dbo.FLOW_Enum.pk
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public Integer getPk() {
        return pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_Enum.pk
     *
     * @param pk the value for dbo.FLOW_Enum.pk
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setPk(Integer pk) {
        this.pk = pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_Enum.gid
     *
     * @return the value of dbo.FLOW_Enum.gid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public String getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_Enum.gid
     *
     * @param gid the value for dbo.FLOW_Enum.gid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setGid(String gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_Enum.enumName
     *
     * @return the value of dbo.FLOW_Enum.enumName
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public String getEnumname() {
        return enumname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_Enum.enumName
     *
     * @param enumname the value for dbo.FLOW_Enum.enumName
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setEnumname(String enumname) {
        this.enumname = enumname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_Enum.description
     *
     * @return the value of dbo.FLOW_Enum.description
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_Enum.description
     *
     * @param description the value for dbo.FLOW_Enum.description
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_Enum.createUserId
     *
     * @return the value of dbo.FLOW_Enum.createUserId
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public String getCreateuserid() {
        return createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_Enum.createUserId
     *
     * @param createuserid the value for dbo.FLOW_Enum.createUserId
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setCreateuserid(String createuserid) {
        this.createuserid = createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_Enum.createTime
     *
     * @return the value of dbo.FLOW_Enum.createTime
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_Enum.createTime
     *
     * @param createtime the value for dbo.FLOW_Enum.createTime
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_Enum.enumType
     *
     * @return the value of dbo.FLOW_Enum.enumType
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public Integer getEnumtype() {
        return enumtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_Enum.enumType
     *
     * @param enumtype the value for dbo.FLOW_Enum.enumType
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setEnumtype(Integer enumtype) {
        this.enumtype = enumtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_Enum.tableName
     *
     * @return the value of dbo.FLOW_Enum.tableName
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public String getTablename() {
        return tablename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_Enum.tableName
     *
     * @param tablename the value for dbo.FLOW_Enum.tableName
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setTablename(String tablename) {
        this.tablename = tablename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_Enum.columnName
     *
     * @return the value of dbo.FLOW_Enum.columnName
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public String getColumnname() {
        return columnname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_Enum.columnName
     *
     * @param columnname the value for dbo.FLOW_Enum.columnName
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setColumnname(String columnname) {
        this.columnname = columnname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.FLOW_Enum.conditionSql
     *
     * @return the value of dbo.FLOW_Enum.conditionSql
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public String getConditionsql() {
        return conditionsql;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.FLOW_Enum.conditionSql
     *
     * @param conditionsql the value for dbo.FLOW_Enum.conditionSql
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setConditionsql(String conditionsql) {
        this.conditionsql = conditionsql;
    }
}