package com.emi.wms.bean;

import java.util.Date;

public class MesAaBox {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_AA_Box.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Integer pk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_AA_Box.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String gid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_AA_Box.barcode
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String barcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_AA_Box.note
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_AA_Box.packtime
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Date packtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_AA_Box.userGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String usergid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_AA_Box.taskGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String taskgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_AA_Box.isUsed
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Integer isused;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_AA_Box.pk
     *
     * @return the value of dbo.MES_AA_Box.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Integer getPk() {
        return pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_AA_Box.pk
     *
     * @param pk the value for dbo.MES_AA_Box.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setPk(Integer pk) {
        this.pk = pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_AA_Box.gid
     *
     * @return the value of dbo.MES_AA_Box.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_AA_Box.gid
     *
     * @param gid the value for dbo.MES_AA_Box.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setGid(String gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_AA_Box.barcode
     *
     * @return the value of dbo.MES_AA_Box.barcode
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getBarcode() {
        return barcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_AA_Box.barcode
     *
     * @param barcode the value for dbo.MES_AA_Box.barcode
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setBarcode(String barcode) {
        this.barcode = barcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_AA_Box.note
     *
     * @return the value of dbo.MES_AA_Box.note
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_AA_Box.note
     *
     * @param note the value for dbo.MES_AA_Box.note
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_AA_Box.packtime
     *
     * @return the value of dbo.MES_AA_Box.packtime
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Date getPacktime() {
        return packtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_AA_Box.packtime
     *
     * @param packtime the value for dbo.MES_AA_Box.packtime
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setPacktime(Date packtime) {
        this.packtime = packtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_AA_Box.userGid
     *
     * @return the value of dbo.MES_AA_Box.userGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getUsergid() {
        return usergid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_AA_Box.userGid
     *
     * @param usergid the value for dbo.MES_AA_Box.userGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setUsergid(String usergid) {
        this.usergid = usergid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_AA_Box.taskGid
     *
     * @return the value of dbo.MES_AA_Box.taskGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getTaskgid() {
        return taskgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_AA_Box.taskGid
     *
     * @param taskgid the value for dbo.MES_AA_Box.taskGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setTaskgid(String taskgid) {
        this.taskgid = taskgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_AA_Box.isUsed
     *
     * @return the value of dbo.MES_AA_Box.isUsed
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Integer getIsused() {
        return isused;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_AA_Box.isUsed
     *
     * @param isused the value for dbo.MES_AA_Box.isUsed
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setIsused(Integer isused) {
        this.isused = isused;
    }
}