package com.emi.wms.bean;

public class MesAaProcesssound {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_AA_ProcessSound.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Integer pk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_AA_ProcessSound.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String gid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_AA_ProcessSound.processGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String processgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_AA_ProcessSound.soundPath
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String soundpath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_AA_ProcessSound.soundCode
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String soundcode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_AA_ProcessSound.pk
     *
     * @return the value of dbo.MES_AA_ProcessSound.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Integer getPk() {
        return pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_AA_ProcessSound.pk
     *
     * @param pk the value for dbo.MES_AA_ProcessSound.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setPk(Integer pk) {
        this.pk = pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_AA_ProcessSound.gid
     *
     * @return the value of dbo.MES_AA_ProcessSound.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_AA_ProcessSound.gid
     *
     * @param gid the value for dbo.MES_AA_ProcessSound.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setGid(String gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_AA_ProcessSound.processGid
     *
     * @return the value of dbo.MES_AA_ProcessSound.processGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getProcessgid() {
        return processgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_AA_ProcessSound.processGid
     *
     * @param processgid the value for dbo.MES_AA_ProcessSound.processGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setProcessgid(String processgid) {
        this.processgid = processgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_AA_ProcessSound.soundPath
     *
     * @return the value of dbo.MES_AA_ProcessSound.soundPath
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getSoundpath() {
        return soundpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_AA_ProcessSound.soundPath
     *
     * @param soundpath the value for dbo.MES_AA_ProcessSound.soundPath
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setSoundpath(String soundpath) {
        this.soundpath = soundpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_AA_ProcessSound.soundCode
     *
     * @return the value of dbo.MES_AA_ProcessSound.soundCode
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getSoundcode() {
        return soundcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_AA_ProcessSound.soundCode
     *
     * @param soundcode the value for dbo.MES_AA_ProcessSound.soundCode
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setSoundcode(String soundcode) {
        this.soundcode = soundcode;
    }
}