package com.emi.wms.bean;

import java.math.BigDecimal;

public class MesAaBoxc {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_AA_BoxC.pk
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    private Integer pk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_AA_BoxC.gid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    private String gid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_AA_BoxC.goodsgid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    private String goodsgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_AA_BoxC.location
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    private String location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_AA_BoxC.num
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    private BigDecimal num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_AA_BoxC.batch
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    private String batch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_AA_BoxC.boxbarcode
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    private String boxbarcode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_AA_BoxC.pk
     *
     * @return the value of dbo.MES_AA_BoxC.pk
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public Integer getPk() {
        return pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_AA_BoxC.pk
     *
     * @param pk the value for dbo.MES_AA_BoxC.pk
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setPk(Integer pk) {
        this.pk = pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_AA_BoxC.gid
     *
     * @return the value of dbo.MES_AA_BoxC.gid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public String getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_AA_BoxC.gid
     *
     * @param gid the value for dbo.MES_AA_BoxC.gid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setGid(String gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_AA_BoxC.goodsgid
     *
     * @return the value of dbo.MES_AA_BoxC.goodsgid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public String getGoodsgid() {
        return goodsgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_AA_BoxC.goodsgid
     *
     * @param goodsgid the value for dbo.MES_AA_BoxC.goodsgid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setGoodsgid(String goodsgid) {
        this.goodsgid = goodsgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_AA_BoxC.location
     *
     * @return the value of dbo.MES_AA_BoxC.location
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_AA_BoxC.location
     *
     * @param location the value for dbo.MES_AA_BoxC.location
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setLocation(String location) {
        this.location = location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_AA_BoxC.num
     *
     * @return the value of dbo.MES_AA_BoxC.num
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public BigDecimal getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_AA_BoxC.num
     *
     * @param num the value for dbo.MES_AA_BoxC.num
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setNum(BigDecimal num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_AA_BoxC.batch
     *
     * @return the value of dbo.MES_AA_BoxC.batch
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public String getBatch() {
        return batch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_AA_BoxC.batch
     *
     * @param batch the value for dbo.MES_AA_BoxC.batch
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setBatch(String batch) {
        this.batch = batch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_AA_BoxC.boxbarcode
     *
     * @return the value of dbo.MES_AA_BoxC.boxbarcode
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public String getBoxbarcode() {
        return boxbarcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_AA_BoxC.boxbarcode
     *
     * @param boxbarcode the value for dbo.MES_AA_BoxC.boxbarcode
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setBoxbarcode(String boxbarcode) {
        this.boxbarcode = boxbarcode;
    }
}