package com.emi.wms.bean;

import java.math.BigDecimal;

public class MesAaIngredient {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_AA_Ingredient.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Integer pk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_AA_Ingredient.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String gid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_AA_Ingredient.notes
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String notes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_AA_Ingredient.processGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String processgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_AA_Ingredient.processCode
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String processcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_AA_Ingredient.goodsGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String goodsgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_AA_Ingredient.quantity
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private BigDecimal quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_AA_Ingredient.goodsSort
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String goodssort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_AA_Ingredient.sobGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String sobgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_AA_Ingredient.orgGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String orggid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_AA_Ingredient.pk
     *
     * @return the value of dbo.MES_AA_Ingredient.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Integer getPk() {
        return pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_AA_Ingredient.pk
     *
     * @param pk the value for dbo.MES_AA_Ingredient.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setPk(Integer pk) {
        this.pk = pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_AA_Ingredient.gid
     *
     * @return the value of dbo.MES_AA_Ingredient.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_AA_Ingredient.gid
     *
     * @param gid the value for dbo.MES_AA_Ingredient.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setGid(String gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_AA_Ingredient.notes
     *
     * @return the value of dbo.MES_AA_Ingredient.notes
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_AA_Ingredient.notes
     *
     * @param notes the value for dbo.MES_AA_Ingredient.notes
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setNotes(String notes) {
        this.notes = notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_AA_Ingredient.processGid
     *
     * @return the value of dbo.MES_AA_Ingredient.processGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getProcessgid() {
        return processgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_AA_Ingredient.processGid
     *
     * @param processgid the value for dbo.MES_AA_Ingredient.processGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setProcessgid(String processgid) {
        this.processgid = processgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_AA_Ingredient.processCode
     *
     * @return the value of dbo.MES_AA_Ingredient.processCode
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getProcesscode() {
        return processcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_AA_Ingredient.processCode
     *
     * @param processcode the value for dbo.MES_AA_Ingredient.processCode
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setProcesscode(String processcode) {
        this.processcode = processcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_AA_Ingredient.goodsGid
     *
     * @return the value of dbo.MES_AA_Ingredient.goodsGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getGoodsgid() {
        return goodsgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_AA_Ingredient.goodsGid
     *
     * @param goodsgid the value for dbo.MES_AA_Ingredient.goodsGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setGoodsgid(String goodsgid) {
        this.goodsgid = goodsgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_AA_Ingredient.quantity
     *
     * @return the value of dbo.MES_AA_Ingredient.quantity
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public BigDecimal getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_AA_Ingredient.quantity
     *
     * @param quantity the value for dbo.MES_AA_Ingredient.quantity
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setQuantity(BigDecimal quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_AA_Ingredient.goodsSort
     *
     * @return the value of dbo.MES_AA_Ingredient.goodsSort
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getGoodssort() {
        return goodssort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_AA_Ingredient.goodsSort
     *
     * @param goodssort the value for dbo.MES_AA_Ingredient.goodsSort
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setGoodssort(String goodssort) {
        this.goodssort = goodssort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_AA_Ingredient.sobGid
     *
     * @return the value of dbo.MES_AA_Ingredient.sobGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getSobgid() {
        return sobgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_AA_Ingredient.sobGid
     *
     * @param sobgid the value for dbo.MES_AA_Ingredient.sobGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setSobgid(String sobgid) {
        this.sobgid = sobgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_AA_Ingredient.orgGid
     *
     * @return the value of dbo.MES_AA_Ingredient.orgGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getOrggid() {
        return orggid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_AA_Ingredient.orgGid
     *
     * @param orggid the value for dbo.MES_AA_Ingredient.orgGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setOrggid(String orggid) {
        this.orggid = orggid;
    }
}