package com.emi.wms.bean;

public class MesWmOrderprocessroute {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_OrderProcessRoute.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Integer pk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_OrderProcessRoute.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String gid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_OrderProcessRoute.routGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String routgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_OrderProcessRoute.produceOrderCUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String produceordercuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_OrderProcessRoute.produceOrderUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String produceorderuid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_OrderProcessRoute.pk
     *
     * @return the value of dbo.MES_WM_OrderProcessRoute.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Integer getPk() {
        return pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_OrderProcessRoute.pk
     *
     * @param pk the value for dbo.MES_WM_OrderProcessRoute.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setPk(Integer pk) {
        this.pk = pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_OrderProcessRoute.gid
     *
     * @return the value of dbo.MES_WM_OrderProcessRoute.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_OrderProcessRoute.gid
     *
     * @param gid the value for dbo.MES_WM_OrderProcessRoute.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setGid(String gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_OrderProcessRoute.routGid
     *
     * @return the value of dbo.MES_WM_OrderProcessRoute.routGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getRoutgid() {
        return routgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_OrderProcessRoute.routGid
     *
     * @param routgid the value for dbo.MES_WM_OrderProcessRoute.routGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setRoutgid(String routgid) {
        this.routgid = routgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_OrderProcessRoute.produceOrderCUid
     *
     * @return the value of dbo.MES_WM_OrderProcessRoute.produceOrderCUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getProduceordercuid() {
        return produceordercuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_OrderProcessRoute.produceOrderCUid
     *
     * @param produceordercuid the value for dbo.MES_WM_OrderProcessRoute.produceOrderCUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setProduceordercuid(String produceordercuid) {
        this.produceordercuid = produceordercuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_OrderProcessRoute.produceOrderUid
     *
     * @return the value of dbo.MES_WM_OrderProcessRoute.produceOrderUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getProduceorderuid() {
        return produceorderuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_OrderProcessRoute.produceOrderUid
     *
     * @param produceorderuid the value for dbo.MES_WM_OrderProcessRoute.produceOrderUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setProduceorderuid(String produceorderuid) {
        this.produceorderuid = produceorderuid;
    }
}