package com.emi.wms.bean;

import java.math.BigDecimal;

public class MesWmIngrecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_IngRecord.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Integer pk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_IngRecord.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String gid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_IngRecord.taskGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String taskgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_IngRecord.goodsGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String goodsgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_IngRecord.quantity
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private BigDecimal quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_IngRecord.inquantity
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private BigDecimal inquantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_IngRecord.WIPType
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Integer wiptype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_IngRecord.preOrderGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String preordergid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_IngRecord.poDetails
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String podetails;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_IngRecord.sobGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String sobgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_IngRecord.orgGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String orggid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_IngRecord.pk
     *
     * @return the value of dbo.MES_WM_IngRecord.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Integer getPk() {
        return pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_IngRecord.pk
     *
     * @param pk the value for dbo.MES_WM_IngRecord.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setPk(Integer pk) {
        this.pk = pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_IngRecord.gid
     *
     * @return the value of dbo.MES_WM_IngRecord.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_IngRecord.gid
     *
     * @param gid the value for dbo.MES_WM_IngRecord.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setGid(String gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_IngRecord.taskGid
     *
     * @return the value of dbo.MES_WM_IngRecord.taskGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getTaskgid() {
        return taskgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_IngRecord.taskGid
     *
     * @param taskgid the value for dbo.MES_WM_IngRecord.taskGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setTaskgid(String taskgid) {
        this.taskgid = taskgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_IngRecord.goodsGid
     *
     * @return the value of dbo.MES_WM_IngRecord.goodsGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getGoodsgid() {
        return goodsgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_IngRecord.goodsGid
     *
     * @param goodsgid the value for dbo.MES_WM_IngRecord.goodsGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setGoodsgid(String goodsgid) {
        this.goodsgid = goodsgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_IngRecord.quantity
     *
     * @return the value of dbo.MES_WM_IngRecord.quantity
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public BigDecimal getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_IngRecord.quantity
     *
     * @param quantity the value for dbo.MES_WM_IngRecord.quantity
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setQuantity(BigDecimal quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_IngRecord.inquantity
     *
     * @return the value of dbo.MES_WM_IngRecord.inquantity
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public BigDecimal getInquantity() {
        return inquantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_IngRecord.inquantity
     *
     * @param inquantity the value for dbo.MES_WM_IngRecord.inquantity
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setInquantity(BigDecimal inquantity) {
        this.inquantity = inquantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_IngRecord.WIPType
     *
     * @return the value of dbo.MES_WM_IngRecord.WIPType
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Integer getWiptype() {
        return wiptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_IngRecord.WIPType
     *
     * @param wiptype the value for dbo.MES_WM_IngRecord.WIPType
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setWiptype(Integer wiptype) {
        this.wiptype = wiptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_IngRecord.preOrderGid
     *
     * @return the value of dbo.MES_WM_IngRecord.preOrderGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getPreordergid() {
        return preordergid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_IngRecord.preOrderGid
     *
     * @param preordergid the value for dbo.MES_WM_IngRecord.preOrderGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setPreordergid(String preordergid) {
        this.preordergid = preordergid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_IngRecord.poDetails
     *
     * @return the value of dbo.MES_WM_IngRecord.poDetails
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getPodetails() {
        return podetails;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_IngRecord.poDetails
     *
     * @param podetails the value for dbo.MES_WM_IngRecord.poDetails
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setPodetails(String podetails) {
        this.podetails = podetails;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_IngRecord.sobGid
     *
     * @return the value of dbo.MES_WM_IngRecord.sobGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getSobgid() {
        return sobgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_IngRecord.sobGid
     *
     * @param sobgid the value for dbo.MES_WM_IngRecord.sobGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setSobgid(String sobgid) {
        this.sobgid = sobgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_IngRecord.orgGid
     *
     * @return the value of dbo.MES_WM_IngRecord.orgGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getOrggid() {
        return orggid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_IngRecord.orgGid
     *
     * @param orggid the value for dbo.MES_WM_IngRecord.orgGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setOrggid(String orggid) {
        this.orggid = orggid;
    }
}