package com.emi.wms.bean;

public class MesWmProofingcardImg {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_ProofingCard_Img.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Integer pk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_ProofingCard_Img.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String gid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_ProofingCard_Img.cardGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String cardgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_ProofingCard_Img.img
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String img;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_ProofingCard_Img.pk
     *
     * @return the value of dbo.MES_WM_ProofingCard_Img.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Integer getPk() {
        return pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_ProofingCard_Img.pk
     *
     * @param pk the value for dbo.MES_WM_ProofingCard_Img.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setPk(Integer pk) {
        this.pk = pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_ProofingCard_Img.gid
     *
     * @return the value of dbo.MES_WM_ProofingCard_Img.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_ProofingCard_Img.gid
     *
     * @param gid the value for dbo.MES_WM_ProofingCard_Img.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setGid(String gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_ProofingCard_Img.cardGid
     *
     * @return the value of dbo.MES_WM_ProofingCard_Img.cardGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getCardgid() {
        return cardgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_ProofingCard_Img.cardGid
     *
     * @param cardgid the value for dbo.MES_WM_ProofingCard_Img.cardGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setCardgid(String cardgid) {
        this.cardgid = cardgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_ProofingCard_Img.img
     *
     * @return the value of dbo.MES_WM_ProofingCard_Img.img
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_ProofingCard_Img.img
     *
     * @param img the value for dbo.MES_WM_ProofingCard_Img.img
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setImg(String img) {
        this.img = img;
    }
}