package com.emi.wms.bean;

import java.util.Date;

public class MesWmBarcoderecodec {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_BarcodeRecodeC.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Integer pk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_BarcodeRecodeC.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String gid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_BarcodeRecodeC.recodeGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String recodegid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_BarcodeRecodeC.number
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Integer number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_BarcodeRecodeC.printTime
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Date printtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_BarcodeRecodeC.pk
     *
     * @return the value of dbo.MES_WM_BarcodeRecodeC.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Integer getPk() {
        return pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_BarcodeRecodeC.pk
     *
     * @param pk the value for dbo.MES_WM_BarcodeRecodeC.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setPk(Integer pk) {
        this.pk = pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_BarcodeRecodeC.gid
     *
     * @return the value of dbo.MES_WM_BarcodeRecodeC.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_BarcodeRecodeC.gid
     *
     * @param gid the value for dbo.MES_WM_BarcodeRecodeC.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setGid(String gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_BarcodeRecodeC.recodeGid
     *
     * @return the value of dbo.MES_WM_BarcodeRecodeC.recodeGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getRecodegid() {
        return recodegid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_BarcodeRecodeC.recodeGid
     *
     * @param recodegid the value for dbo.MES_WM_BarcodeRecodeC.recodeGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setRecodegid(String recodegid) {
        this.recodegid = recodegid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_BarcodeRecodeC.number
     *
     * @return the value of dbo.MES_WM_BarcodeRecodeC.number
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_BarcodeRecodeC.number
     *
     * @param number the value for dbo.MES_WM_BarcodeRecodeC.number
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_BarcodeRecodeC.printTime
     *
     * @return the value of dbo.MES_WM_BarcodeRecodeC.printTime
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Date getPrinttime() {
        return printtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_BarcodeRecodeC.printTime
     *
     * @param printtime the value for dbo.MES_WM_BarcodeRecodeC.printTime
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setPrinttime(Date printtime) {
        this.printtime = printtime;
    }
}