package com.emi.wms.bean;

import java.util.Date;

public class MesWmTask {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_Task.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Integer pk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_Task.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String gid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_Task.notes
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String notes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_Task.taskBarcode
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String taskbarcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_Task.taskName
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String taskname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_Task.dispatchTime
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Date dispatchtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_Task.dispatchUserUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String dispatchuseruid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_Task.beginTime
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Date begintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_Task.endTime
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Date endtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_Task.shouldEndTime
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Date shouldendtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_Task.isAccept
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Integer isaccept;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_Task.taskStatus
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Integer taskstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_Task.isActive
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Integer isactive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_Task.dispatchingCgid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String dispatchingcgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_Task.recipientGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String recipientgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_Task.taskType
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String tasktype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_Task.aptRecUserUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String aptrecuseruid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_Task.aptRecRoleUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String aptrecroleuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_Task.aptRecDeptuid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String aptrecdeptuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_Task.preTaskGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String pretaskgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_Task.produceOrderId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String produceorderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_Task.produceOrderCode
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String produceordercode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_Task.islast
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Integer islast;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_Task.isNeedDo
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Integer isneeddo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_Task.produceOrderCId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String produceordercid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_Task.checkId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String checkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_Task.unitGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String unitgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_Task.unitFlag
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Integer unitflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_Task.sobId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String sobid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_Task.orgId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String orgid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_Task.pk
     *
     * @return the value of dbo.MES_WM_Task.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Integer getPk() {
        return pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_Task.pk
     *
     * @param pk the value for dbo.MES_WM_Task.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setPk(Integer pk) {
        this.pk = pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_Task.gid
     *
     * @return the value of dbo.MES_WM_Task.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_Task.gid
     *
     * @param gid the value for dbo.MES_WM_Task.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setGid(String gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_Task.notes
     *
     * @return the value of dbo.MES_WM_Task.notes
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_Task.notes
     *
     * @param notes the value for dbo.MES_WM_Task.notes
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setNotes(String notes) {
        this.notes = notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_Task.taskBarcode
     *
     * @return the value of dbo.MES_WM_Task.taskBarcode
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getTaskbarcode() {
        return taskbarcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_Task.taskBarcode
     *
     * @param taskbarcode the value for dbo.MES_WM_Task.taskBarcode
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setTaskbarcode(String taskbarcode) {
        this.taskbarcode = taskbarcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_Task.taskName
     *
     * @return the value of dbo.MES_WM_Task.taskName
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getTaskname() {
        return taskname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_Task.taskName
     *
     * @param taskname the value for dbo.MES_WM_Task.taskName
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setTaskname(String taskname) {
        this.taskname = taskname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_Task.dispatchTime
     *
     * @return the value of dbo.MES_WM_Task.dispatchTime
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Date getDispatchtime() {
        return dispatchtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_Task.dispatchTime
     *
     * @param dispatchtime the value for dbo.MES_WM_Task.dispatchTime
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setDispatchtime(Date dispatchtime) {
        this.dispatchtime = dispatchtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_Task.dispatchUserUid
     *
     * @return the value of dbo.MES_WM_Task.dispatchUserUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getDispatchuseruid() {
        return dispatchuseruid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_Task.dispatchUserUid
     *
     * @param dispatchuseruid the value for dbo.MES_WM_Task.dispatchUserUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setDispatchuseruid(String dispatchuseruid) {
        this.dispatchuseruid = dispatchuseruid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_Task.beginTime
     *
     * @return the value of dbo.MES_WM_Task.beginTime
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Date getBegintime() {
        return begintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_Task.beginTime
     *
     * @param begintime the value for dbo.MES_WM_Task.beginTime
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setBegintime(Date begintime) {
        this.begintime = begintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_Task.endTime
     *
     * @return the value of dbo.MES_WM_Task.endTime
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_Task.endTime
     *
     * @param endtime the value for dbo.MES_WM_Task.endTime
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_Task.shouldEndTime
     *
     * @return the value of dbo.MES_WM_Task.shouldEndTime
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Date getShouldendtime() {
        return shouldendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_Task.shouldEndTime
     *
     * @param shouldendtime the value for dbo.MES_WM_Task.shouldEndTime
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setShouldendtime(Date shouldendtime) {
        this.shouldendtime = shouldendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_Task.isAccept
     *
     * @return the value of dbo.MES_WM_Task.isAccept
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Integer getIsaccept() {
        return isaccept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_Task.isAccept
     *
     * @param isaccept the value for dbo.MES_WM_Task.isAccept
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setIsaccept(Integer isaccept) {
        this.isaccept = isaccept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_Task.taskStatus
     *
     * @return the value of dbo.MES_WM_Task.taskStatus
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Integer getTaskstatus() {
        return taskstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_Task.taskStatus
     *
     * @param taskstatus the value for dbo.MES_WM_Task.taskStatus
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setTaskstatus(Integer taskstatus) {
        this.taskstatus = taskstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_Task.isActive
     *
     * @return the value of dbo.MES_WM_Task.isActive
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Integer getIsactive() {
        return isactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_Task.isActive
     *
     * @param isactive the value for dbo.MES_WM_Task.isActive
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setIsactive(Integer isactive) {
        this.isactive = isactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_Task.dispatchingCgid
     *
     * @return the value of dbo.MES_WM_Task.dispatchingCgid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getDispatchingcgid() {
        return dispatchingcgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_Task.dispatchingCgid
     *
     * @param dispatchingcgid the value for dbo.MES_WM_Task.dispatchingCgid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setDispatchingcgid(String dispatchingcgid) {
        this.dispatchingcgid = dispatchingcgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_Task.recipientGid
     *
     * @return the value of dbo.MES_WM_Task.recipientGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getRecipientgid() {
        return recipientgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_Task.recipientGid
     *
     * @param recipientgid the value for dbo.MES_WM_Task.recipientGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setRecipientgid(String recipientgid) {
        this.recipientgid = recipientgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_Task.taskType
     *
     * @return the value of dbo.MES_WM_Task.taskType
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getTasktype() {
        return tasktype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_Task.taskType
     *
     * @param tasktype the value for dbo.MES_WM_Task.taskType
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setTasktype(String tasktype) {
        this.tasktype = tasktype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_Task.aptRecUserUid
     *
     * @return the value of dbo.MES_WM_Task.aptRecUserUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getAptrecuseruid() {
        return aptrecuseruid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_Task.aptRecUserUid
     *
     * @param aptrecuseruid the value for dbo.MES_WM_Task.aptRecUserUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setAptrecuseruid(String aptrecuseruid) {
        this.aptrecuseruid = aptrecuseruid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_Task.aptRecRoleUid
     *
     * @return the value of dbo.MES_WM_Task.aptRecRoleUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getAptrecroleuid() {
        return aptrecroleuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_Task.aptRecRoleUid
     *
     * @param aptrecroleuid the value for dbo.MES_WM_Task.aptRecRoleUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setAptrecroleuid(String aptrecroleuid) {
        this.aptrecroleuid = aptrecroleuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_Task.aptRecDeptuid
     *
     * @return the value of dbo.MES_WM_Task.aptRecDeptuid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getAptrecdeptuid() {
        return aptrecdeptuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_Task.aptRecDeptuid
     *
     * @param aptrecdeptuid the value for dbo.MES_WM_Task.aptRecDeptuid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setAptrecdeptuid(String aptrecdeptuid) {
        this.aptrecdeptuid = aptrecdeptuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_Task.preTaskGid
     *
     * @return the value of dbo.MES_WM_Task.preTaskGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getPretaskgid() {
        return pretaskgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_Task.preTaskGid
     *
     * @param pretaskgid the value for dbo.MES_WM_Task.preTaskGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setPretaskgid(String pretaskgid) {
        this.pretaskgid = pretaskgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_Task.produceOrderId
     *
     * @return the value of dbo.MES_WM_Task.produceOrderId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getProduceorderid() {
        return produceorderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_Task.produceOrderId
     *
     * @param produceorderid the value for dbo.MES_WM_Task.produceOrderId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setProduceorderid(String produceorderid) {
        this.produceorderid = produceorderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_Task.produceOrderCode
     *
     * @return the value of dbo.MES_WM_Task.produceOrderCode
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getProduceordercode() {
        return produceordercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_Task.produceOrderCode
     *
     * @param produceordercode the value for dbo.MES_WM_Task.produceOrderCode
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setProduceordercode(String produceordercode) {
        this.produceordercode = produceordercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_Task.islast
     *
     * @return the value of dbo.MES_WM_Task.islast
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Integer getIslast() {
        return islast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_Task.islast
     *
     * @param islast the value for dbo.MES_WM_Task.islast
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setIslast(Integer islast) {
        this.islast = islast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_Task.isNeedDo
     *
     * @return the value of dbo.MES_WM_Task.isNeedDo
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Integer getIsneeddo() {
        return isneeddo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_Task.isNeedDo
     *
     * @param isneeddo the value for dbo.MES_WM_Task.isNeedDo
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setIsneeddo(Integer isneeddo) {
        this.isneeddo = isneeddo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_Task.produceOrderCId
     *
     * @return the value of dbo.MES_WM_Task.produceOrderCId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getProduceordercid() {
        return produceordercid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_Task.produceOrderCId
     *
     * @param produceordercid the value for dbo.MES_WM_Task.produceOrderCId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setProduceordercid(String produceordercid) {
        this.produceordercid = produceordercid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_Task.checkId
     *
     * @return the value of dbo.MES_WM_Task.checkId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getCheckid() {
        return checkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_Task.checkId
     *
     * @param checkid the value for dbo.MES_WM_Task.checkId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setCheckid(String checkid) {
        this.checkid = checkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_Task.unitGid
     *
     * @return the value of dbo.MES_WM_Task.unitGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getUnitgid() {
        return unitgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_Task.unitGid
     *
     * @param unitgid the value for dbo.MES_WM_Task.unitGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setUnitgid(String unitgid) {
        this.unitgid = unitgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_Task.unitFlag
     *
     * @return the value of dbo.MES_WM_Task.unitFlag
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Integer getUnitflag() {
        return unitflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_Task.unitFlag
     *
     * @param unitflag the value for dbo.MES_WM_Task.unitFlag
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setUnitflag(Integer unitflag) {
        this.unitflag = unitflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_Task.sobId
     *
     * @return the value of dbo.MES_WM_Task.sobId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getSobid() {
        return sobid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_Task.sobId
     *
     * @param sobid the value for dbo.MES_WM_Task.sobId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setSobid(String sobid) {
        this.sobid = sobid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_Task.orgId
     *
     * @return the value of dbo.MES_WM_Task.orgId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getOrgid() {
        return orgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_Task.orgId
     *
     * @param orgid the value for dbo.MES_WM_Task.orgId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setOrgid(String orgid) {
        this.orgid = orgid;
    }
}