package com.emi.wms.bean;

public class MesWmCommoninformat {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_CommonInformat.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Integer pk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_CommonInformat.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String gid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_CommonInformat.documentType
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String documenttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_CommonInformat.sobGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String sobgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_CommonInformat.orgId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String orgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_CommonInformat.customterUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String customteruid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_CommonInformat.collectionField
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String collectionfield;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_CommonInformat.collectionCode
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String collectioncode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_CommonInformat.collectionName
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String collectionname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_CommonInformat.flag
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Integer flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_CommonInformat.collectionFieldGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String collectionfieldgid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_CommonInformat.pk
     *
     * @return the value of dbo.MES_WM_CommonInformat.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Integer getPk() {
        return pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_CommonInformat.pk
     *
     * @param pk the value for dbo.MES_WM_CommonInformat.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setPk(Integer pk) {
        this.pk = pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_CommonInformat.gid
     *
     * @return the value of dbo.MES_WM_CommonInformat.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_CommonInformat.gid
     *
     * @param gid the value for dbo.MES_WM_CommonInformat.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setGid(String gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_CommonInformat.documentType
     *
     * @return the value of dbo.MES_WM_CommonInformat.documentType
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getDocumenttype() {
        return documenttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_CommonInformat.documentType
     *
     * @param documenttype the value for dbo.MES_WM_CommonInformat.documentType
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setDocumenttype(String documenttype) {
        this.documenttype = documenttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_CommonInformat.sobGid
     *
     * @return the value of dbo.MES_WM_CommonInformat.sobGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getSobgid() {
        return sobgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_CommonInformat.sobGid
     *
     * @param sobgid the value for dbo.MES_WM_CommonInformat.sobGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setSobgid(String sobgid) {
        this.sobgid = sobgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_CommonInformat.orgId
     *
     * @return the value of dbo.MES_WM_CommonInformat.orgId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getOrgid() {
        return orgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_CommonInformat.orgId
     *
     * @param orgid the value for dbo.MES_WM_CommonInformat.orgId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setOrgid(String orgid) {
        this.orgid = orgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_CommonInformat.customterUid
     *
     * @return the value of dbo.MES_WM_CommonInformat.customterUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getCustomteruid() {
        return customteruid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_CommonInformat.customterUid
     *
     * @param customteruid the value for dbo.MES_WM_CommonInformat.customterUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setCustomteruid(String customteruid) {
        this.customteruid = customteruid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_CommonInformat.collectionField
     *
     * @return the value of dbo.MES_WM_CommonInformat.collectionField
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getCollectionfield() {
        return collectionfield;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_CommonInformat.collectionField
     *
     * @param collectionfield the value for dbo.MES_WM_CommonInformat.collectionField
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setCollectionfield(String collectionfield) {
        this.collectionfield = collectionfield;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_CommonInformat.collectionCode
     *
     * @return the value of dbo.MES_WM_CommonInformat.collectionCode
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getCollectioncode() {
        return collectioncode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_CommonInformat.collectionCode
     *
     * @param collectioncode the value for dbo.MES_WM_CommonInformat.collectionCode
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setCollectioncode(String collectioncode) {
        this.collectioncode = collectioncode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_CommonInformat.collectionName
     *
     * @return the value of dbo.MES_WM_CommonInformat.collectionName
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getCollectionname() {
        return collectionname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_CommonInformat.collectionName
     *
     * @param collectionname the value for dbo.MES_WM_CommonInformat.collectionName
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setCollectionname(String collectionname) {
        this.collectionname = collectionname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_CommonInformat.flag
     *
     * @return the value of dbo.MES_WM_CommonInformat.flag
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_CommonInformat.flag
     *
     * @param flag the value for dbo.MES_WM_CommonInformat.flag
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_CommonInformat.collectionFieldGid
     *
     * @return the value of dbo.MES_WM_CommonInformat.collectionFieldGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getCollectionfieldgid() {
        return collectionfieldgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_CommonInformat.collectionFieldGid
     *
     * @param collectionfieldgid the value for dbo.MES_WM_CommonInformat.collectionFieldGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setCollectionfieldgid(String collectionfieldgid) {
        this.collectionfieldgid = collectionfieldgid;
    }
}