package com.emi.wms.bean;

public class MesWmProofingcardcProcess {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_ProofingCardC_Process.pk
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    private Integer pk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_ProofingCardC_Process.gid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    private String gid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_ProofingCardC_Process.pcardGid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    private String pcardgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_ProofingCardC_Process.processGid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    private String processgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_ProofingCardC_Process.pcardcGid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    private String pcardcgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_ProofingCardC_Process.ask
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    private String ask;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_ProofingCardC_Process.processTime
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    private String processtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_ProofingCardC_Process.processUnit
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    private String processunit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_ProofingCardC_Process.userGid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    private String usergid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_ProofingCardC_Process.pk
     *
     * @return the value of dbo.MES_WM_ProofingCardC_Process.pk
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public Integer getPk() {
        return pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_ProofingCardC_Process.pk
     *
     * @param pk the value for dbo.MES_WM_ProofingCardC_Process.pk
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setPk(Integer pk) {
        this.pk = pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_ProofingCardC_Process.gid
     *
     * @return the value of dbo.MES_WM_ProofingCardC_Process.gid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public String getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_ProofingCardC_Process.gid
     *
     * @param gid the value for dbo.MES_WM_ProofingCardC_Process.gid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setGid(String gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_ProofingCardC_Process.pcardGid
     *
     * @return the value of dbo.MES_WM_ProofingCardC_Process.pcardGid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public String getPcardgid() {
        return pcardgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_ProofingCardC_Process.pcardGid
     *
     * @param pcardgid the value for dbo.MES_WM_ProofingCardC_Process.pcardGid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setPcardgid(String pcardgid) {
        this.pcardgid = pcardgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_ProofingCardC_Process.processGid
     *
     * @return the value of dbo.MES_WM_ProofingCardC_Process.processGid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public String getProcessgid() {
        return processgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_ProofingCardC_Process.processGid
     *
     * @param processgid the value for dbo.MES_WM_ProofingCardC_Process.processGid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setProcessgid(String processgid) {
        this.processgid = processgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_ProofingCardC_Process.pcardcGid
     *
     * @return the value of dbo.MES_WM_ProofingCardC_Process.pcardcGid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public String getPcardcgid() {
        return pcardcgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_ProofingCardC_Process.pcardcGid
     *
     * @param pcardcgid the value for dbo.MES_WM_ProofingCardC_Process.pcardcGid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setPcardcgid(String pcardcgid) {
        this.pcardcgid = pcardcgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_ProofingCardC_Process.ask
     *
     * @return the value of dbo.MES_WM_ProofingCardC_Process.ask
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public String getAsk() {
        return ask;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_ProofingCardC_Process.ask
     *
     * @param ask the value for dbo.MES_WM_ProofingCardC_Process.ask
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setAsk(String ask) {
        this.ask = ask;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_ProofingCardC_Process.processTime
     *
     * @return the value of dbo.MES_WM_ProofingCardC_Process.processTime
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public String getProcesstime() {
        return processtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_ProofingCardC_Process.processTime
     *
     * @param processtime the value for dbo.MES_WM_ProofingCardC_Process.processTime
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setProcesstime(String processtime) {
        this.processtime = processtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_ProofingCardC_Process.processUnit
     *
     * @return the value of dbo.MES_WM_ProofingCardC_Process.processUnit
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public String getProcessunit() {
        return processunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_ProofingCardC_Process.processUnit
     *
     * @param processunit the value for dbo.MES_WM_ProofingCardC_Process.processUnit
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setProcessunit(String processunit) {
        this.processunit = processunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_ProofingCardC_Process.userGid
     *
     * @return the value of dbo.MES_WM_ProofingCardC_Process.userGid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public String getUsergid() {
        return usergid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_ProofingCardC_Process.userGid
     *
     * @param usergid the value for dbo.MES_WM_ProofingCardC_Process.userGid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setUsergid(String usergid) {
        this.usergid = usergid;
    }
}