package com.emi.wms.bean;

import java.math.BigDecimal;
import java.util.Date;

public class MesWmNumberunlock {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_NumberunLock.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Integer pk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_NumberunLock.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String gid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_NumberunLock.lockGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String lockgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_NumberunLock.saleOrderUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String saleorderuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_NumberunLock.number
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private BigDecimal number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_NumberunLock.unlockTime
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Date unlocktime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_NumberunLock.lockType
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String locktype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_NumberunLock.pk
     *
     * @return the value of dbo.MES_WM_NumberunLock.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Integer getPk() {
        return pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_NumberunLock.pk
     *
     * @param pk the value for dbo.MES_WM_NumberunLock.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setPk(Integer pk) {
        this.pk = pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_NumberunLock.gid
     *
     * @return the value of dbo.MES_WM_NumberunLock.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_NumberunLock.gid
     *
     * @param gid the value for dbo.MES_WM_NumberunLock.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setGid(String gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_NumberunLock.lockGid
     *
     * @return the value of dbo.MES_WM_NumberunLock.lockGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getLockgid() {
        return lockgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_NumberunLock.lockGid
     *
     * @param lockgid the value for dbo.MES_WM_NumberunLock.lockGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setLockgid(String lockgid) {
        this.lockgid = lockgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_NumberunLock.saleOrderUid
     *
     * @return the value of dbo.MES_WM_NumberunLock.saleOrderUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getSaleorderuid() {
        return saleorderuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_NumberunLock.saleOrderUid
     *
     * @param saleorderuid the value for dbo.MES_WM_NumberunLock.saleOrderUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setSaleorderuid(String saleorderuid) {
        this.saleorderuid = saleorderuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_NumberunLock.number
     *
     * @return the value of dbo.MES_WM_NumberunLock.number
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public BigDecimal getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_NumberunLock.number
     *
     * @param number the value for dbo.MES_WM_NumberunLock.number
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setNumber(BigDecimal number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_NumberunLock.unlockTime
     *
     * @return the value of dbo.MES_WM_NumberunLock.unlockTime
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Date getUnlocktime() {
        return unlocktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_NumberunLock.unlockTime
     *
     * @param unlocktime the value for dbo.MES_WM_NumberunLock.unlockTime
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setUnlocktime(Date unlocktime) {
        this.unlocktime = unlocktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_NumberunLock.lockType
     *
     * @return the value of dbo.MES_WM_NumberunLock.lockType
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getLocktype() {
        return locktype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_NumberunLock.lockType
     *
     * @param locktype the value for dbo.MES_WM_NumberunLock.lockType
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setLocktype(String locktype) {
        this.locktype = locktype;
    }
}