package com.emi.wms.bean;

import java.math.BigDecimal;

public class MesWmProductstructurec {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_ProductStructureC.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Integer pk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_ProductStructureC.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String gid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_ProductStructureC.parentCode
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String parentcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_ProductStructureC.wasteRate
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private BigDecimal wasterate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_ProductStructureC.mainUnit
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String mainunit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_ProductStructureC.technology
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String technology;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_ProductStructureC.Process
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String process;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_ProductStructureC.goodsCode
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String goodscode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_ProductStructureC.auxiliaryUnit
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String auxiliaryunit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_ProductStructureC.mainAmount
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private BigDecimal mainamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_ProductStructureC.auxiliaryAmount
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private BigDecimal auxiliaryamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_ProductStructureC.sobGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String sobgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_ProductStructureC.orgGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String orggid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_ProductStructureC.pk
     *
     * @return the value of dbo.MES_WM_ProductStructureC.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Integer getPk() {
        return pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_ProductStructureC.pk
     *
     * @param pk the value for dbo.MES_WM_ProductStructureC.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setPk(Integer pk) {
        this.pk = pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_ProductStructureC.gid
     *
     * @return the value of dbo.MES_WM_ProductStructureC.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_ProductStructureC.gid
     *
     * @param gid the value for dbo.MES_WM_ProductStructureC.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setGid(String gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_ProductStructureC.parentCode
     *
     * @return the value of dbo.MES_WM_ProductStructureC.parentCode
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getParentcode() {
        return parentcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_ProductStructureC.parentCode
     *
     * @param parentcode the value for dbo.MES_WM_ProductStructureC.parentCode
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setParentcode(String parentcode) {
        this.parentcode = parentcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_ProductStructureC.wasteRate
     *
     * @return the value of dbo.MES_WM_ProductStructureC.wasteRate
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public BigDecimal getWasterate() {
        return wasterate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_ProductStructureC.wasteRate
     *
     * @param wasterate the value for dbo.MES_WM_ProductStructureC.wasteRate
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setWasterate(BigDecimal wasterate) {
        this.wasterate = wasterate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_ProductStructureC.mainUnit
     *
     * @return the value of dbo.MES_WM_ProductStructureC.mainUnit
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getMainunit() {
        return mainunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_ProductStructureC.mainUnit
     *
     * @param mainunit the value for dbo.MES_WM_ProductStructureC.mainUnit
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setMainunit(String mainunit) {
        this.mainunit = mainunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_ProductStructureC.technology
     *
     * @return the value of dbo.MES_WM_ProductStructureC.technology
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getTechnology() {
        return technology;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_ProductStructureC.technology
     *
     * @param technology the value for dbo.MES_WM_ProductStructureC.technology
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setTechnology(String technology) {
        this.technology = technology;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_ProductStructureC.Process
     *
     * @return the value of dbo.MES_WM_ProductStructureC.Process
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getProcess() {
        return process;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_ProductStructureC.Process
     *
     * @param process the value for dbo.MES_WM_ProductStructureC.Process
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setProcess(String process) {
        this.process = process;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_ProductStructureC.goodsCode
     *
     * @return the value of dbo.MES_WM_ProductStructureC.goodsCode
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getGoodscode() {
        return goodscode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_ProductStructureC.goodsCode
     *
     * @param goodscode the value for dbo.MES_WM_ProductStructureC.goodsCode
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setGoodscode(String goodscode) {
        this.goodscode = goodscode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_ProductStructureC.auxiliaryUnit
     *
     * @return the value of dbo.MES_WM_ProductStructureC.auxiliaryUnit
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getAuxiliaryunit() {
        return auxiliaryunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_ProductStructureC.auxiliaryUnit
     *
     * @param auxiliaryunit the value for dbo.MES_WM_ProductStructureC.auxiliaryUnit
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setAuxiliaryunit(String auxiliaryunit) {
        this.auxiliaryunit = auxiliaryunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_ProductStructureC.mainAmount
     *
     * @return the value of dbo.MES_WM_ProductStructureC.mainAmount
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public BigDecimal getMainamount() {
        return mainamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_ProductStructureC.mainAmount
     *
     * @param mainamount the value for dbo.MES_WM_ProductStructureC.mainAmount
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setMainamount(BigDecimal mainamount) {
        this.mainamount = mainamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_ProductStructureC.auxiliaryAmount
     *
     * @return the value of dbo.MES_WM_ProductStructureC.auxiliaryAmount
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public BigDecimal getAuxiliaryamount() {
        return auxiliaryamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_ProductStructureC.auxiliaryAmount
     *
     * @param auxiliaryamount the value for dbo.MES_WM_ProductStructureC.auxiliaryAmount
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setAuxiliaryamount(BigDecimal auxiliaryamount) {
        this.auxiliaryamount = auxiliaryamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_ProductStructureC.sobGid
     *
     * @return the value of dbo.MES_WM_ProductStructureC.sobGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getSobgid() {
        return sobgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_ProductStructureC.sobGid
     *
     * @param sobgid the value for dbo.MES_WM_ProductStructureC.sobGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setSobgid(String sobgid) {
        this.sobgid = sobgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_ProductStructureC.orgGid
     *
     * @return the value of dbo.MES_WM_ProductStructureC.orgGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getOrggid() {
        return orggid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_ProductStructureC.orgGid
     *
     * @param orggid the value for dbo.MES_WM_ProductStructureC.orgGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setOrggid(String orggid) {
        this.orggid = orggid;
    }
}