package com.emi.wms.bean;

public class MesWmBasicinfor {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_BasicInfor.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Integer pk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_BasicInfor.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String gid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_BasicInfor.planCode
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String plancode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_BasicInfor.planName
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String planname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.MES_WM_BasicInfor.planDescription
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String plandescription;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_BasicInfor.pk
     *
     * @return the value of dbo.MES_WM_BasicInfor.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Integer getPk() {
        return pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_BasicInfor.pk
     *
     * @param pk the value for dbo.MES_WM_BasicInfor.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setPk(Integer pk) {
        this.pk = pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_BasicInfor.gid
     *
     * @return the value of dbo.MES_WM_BasicInfor.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_BasicInfor.gid
     *
     * @param gid the value for dbo.MES_WM_BasicInfor.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setGid(String gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_BasicInfor.planCode
     *
     * @return the value of dbo.MES_WM_BasicInfor.planCode
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getPlancode() {
        return plancode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_BasicInfor.planCode
     *
     * @param plancode the value for dbo.MES_WM_BasicInfor.planCode
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setPlancode(String plancode) {
        this.plancode = plancode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_BasicInfor.planName
     *
     * @return the value of dbo.MES_WM_BasicInfor.planName
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getPlanname() {
        return planname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_BasicInfor.planName
     *
     * @param planname the value for dbo.MES_WM_BasicInfor.planName
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setPlanname(String planname) {
        this.planname = planname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.MES_WM_BasicInfor.planDescription
     *
     * @return the value of dbo.MES_WM_BasicInfor.planDescription
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getPlandescription() {
        return plandescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.MES_WM_BasicInfor.planDescription
     *
     * @param plandescription the value for dbo.MES_WM_BasicInfor.planDescription
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setPlandescription(String plandescription) {
        this.plandescription = plandescription;
    }
}