package com.emi.wms.bean;

import java.math.BigDecimal;

import com.emi.sys.core.annotation.EmiColumn;
import com.emi.sys.core.annotation.EmiTable;

@EmiTable(name="unitConversion")
public class Unitconversion {

	@EmiColumn(increment=true,name="pk")
    private Integer pk;
	
	@EmiColumn(name="gid",ID=true)
    private String gid;
	
	@EmiColumn(name="unitofmeasurement")
    private Integer unitofmeasurement;//计量单位组分类
	
	@EmiColumn(name="mainunit")
    private String mainunit;//主单位
	
	@EmiColumn(name="masterquantity")
    private BigDecimal masterquantity;//主单位数量
	
	@EmiColumn(name="auxiliaryunit")
    private String auxiliaryunit;//辅单位
	
	@EmiColumn(name="auxiliaryquantity")
    private BigDecimal auxiliaryquantity;//辅单位数量
	
	@EmiColumn(name="sobid")
    private String sobid;//帐套编码
	
	@EmiColumn(name="orgid")
    private String orgid;//组织编码
	
	@EmiColumn(name="unitGroupName")
    private String unitGroupName;//计量单位组名称
	
	@EmiColumn(name="isDel")
	private Integer isDel;//是否删除 1删除 0未删除
    
    public Integer getIsDel() {
		return isDel;
	}

	public void setIsDel(Integer isDel) {
		this.isDel = isDel;
	}

	public Integer getUnitofmeasurement() {
		return unitofmeasurement;
	}

	public void setUnitofmeasurement(Integer unitofmeasurement) {
		this.unitofmeasurement = unitofmeasurement;
	}

	public String getUnitGroupName() {
		return unitGroupName;
	}

	public void setUnitGroupName(String unitGroupName) {
		this.unitGroupName = unitGroupName;
	}

	public Integer getPk() {
        return pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.unitConversion.pk
     *
     * @param pk the value for dbo.unitConversion.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setPk(Integer pk) {
        this.pk = pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.unitConversion.gid
     *
     * @return the value of dbo.unitConversion.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.unitConversion.gid
     *
     * @param gid the value for dbo.unitConversion.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setGid(String gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.unitConversion.mainUnit
     *
     * @return the value of dbo.unitConversion.mainUnit
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getMainunit() {
        return mainunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.unitConversion.mainUnit
     *
     * @param mainunit the value for dbo.unitConversion.mainUnit
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setMainunit(String mainunit) {
        this.mainunit = mainunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.unitConversion.masterQuantity
     *
     * @return the value of dbo.unitConversion.masterQuantity
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public BigDecimal getMasterquantity() {
        return masterquantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.unitConversion.masterQuantity
     *
     * @param masterquantity the value for dbo.unitConversion.masterQuantity
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setMasterquantity(BigDecimal masterquantity) {
        this.masterquantity = masterquantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.unitConversion.auxiliaryUnit
     *
     * @return the value of dbo.unitConversion.auxiliaryUnit
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getAuxiliaryunit() {
        return auxiliaryunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.unitConversion.auxiliaryUnit
     *
     * @param auxiliaryunit the value for dbo.unitConversion.auxiliaryUnit
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setAuxiliaryunit(String auxiliaryunit) {
        this.auxiliaryunit = auxiliaryunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.unitConversion.auxiliaryQuantity
     *
     * @return the value of dbo.unitConversion.auxiliaryQuantity
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public BigDecimal getAuxiliaryquantity() {
        return auxiliaryquantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.unitConversion.auxiliaryQuantity
     *
     * @param auxiliaryquantity the value for dbo.unitConversion.auxiliaryQuantity
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setAuxiliaryquantity(BigDecimal auxiliaryquantity) {
        this.auxiliaryquantity = auxiliaryquantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.unitConversion.sobId
     *
     * @return the value of dbo.unitConversion.sobId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getSobid() {
        return sobid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.unitConversion.sobId
     *
     * @param sobid the value for dbo.unitConversion.sobId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setSobid(String sobid) {
        this.sobid = sobid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.unitConversion.orgId
     *
     * @return the value of dbo.unitConversion.orgId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getOrgid() {
        return orgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.unitConversion.orgId
     *
     * @param orgid the value for dbo.unitConversion.orgId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setOrgid(String orgid) {
        this.orgid = orgid;
    }
}