package com.emi.wms.bean;

public class Unitofmeasurement {
 
    private Integer pk;//

    private String gid;//

    private String unitname;//计量单位组类别名称

    private String unitgroupcode;//计量单位组编码

    private String sobid;//帐套编码

    private String orgid;//组织编码
    
    private String unitgroupname;//计量单位组织名称
    
    
    

    public String getUnitgroupname() {
		return unitgroupname;
	}

	public void setUnitgroupname(String unitgroupname) {
		this.unitgroupname = unitgroupname;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.UnitOfMeasurement.pk
     *
     * @return the value of dbo.UnitOfMeasurement.pk
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public Integer getPk() {
        return pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.UnitOfMeasurement.pk
     *
     * @param pk the value for dbo.UnitOfMeasurement.pk
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setPk(Integer pk) {
        this.pk = pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.UnitOfMeasurement.gid
     *
     * @return the value of dbo.UnitOfMeasurement.gid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public String getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.UnitOfMeasurement.gid
     *
     * @param gid the value for dbo.UnitOfMeasurement.gid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setGid(String gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.UnitOfMeasurement.unitName
     *
     * @return the value of dbo.UnitOfMeasurement.unitName
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public String getUnitname() {
        return unitname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.UnitOfMeasurement.unitName
     *
     * @param unitname the value for dbo.UnitOfMeasurement.unitName
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setUnitname(String unitname) {
        this.unitname = unitname;
    }

    



    public String getUnitgroupcode() {
		return unitgroupcode;
	}

	public void setUnitgroupcode(String unitgroupcode) {
		this.unitgroupcode = unitgroupcode;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.UnitOfMeasurement.sobId
     *
     * @return the value of dbo.UnitOfMeasurement.sobId
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public String getSobid() {
        return sobid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.UnitOfMeasurement.sobId
     *
     * @param sobid the value for dbo.UnitOfMeasurement.sobId
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setSobid(String sobid) {
        this.sobid = sobid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.UnitOfMeasurement.orgId
     *
     * @return the value of dbo.UnitOfMeasurement.orgId
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public String getOrgid() {
        return orgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.UnitOfMeasurement.orgId
     *
     * @param orgid the value for dbo.UnitOfMeasurement.orgId
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setOrgid(String orgid) {
        this.orgid = orgid;
    }
}