package com.emi.wms.bean;

import java.util.Date;

public class ViewTaskchain {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.VIEW_TaskChain.taskGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String taskgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.VIEW_TaskChain.cTaskName
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String ctaskname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.VIEW_TaskChain.fromgTaskCuid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String fromgtaskcuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.VIEW_TaskChain.iState
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Integer istate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.VIEW_TaskChain.bLocked
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Boolean blocked;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.VIEW_TaskChain.taskCompleteTime
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Date taskcompletetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.VIEW_TaskChain.taskCGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String taskcgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.VIEW_TaskChain.dDistributeTime
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Date ddistributetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.VIEW_TaskChain.dShouldCpltTime
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Date dshouldcplttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.VIEW_TaskChain.gAptRecDeptuid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String gaptrecdeptuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.VIEW_TaskChain.gAptRecRoleUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String gaptrecroleuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.VIEW_TaskChain.gAptRecUserUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String gaptrecuseruid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.VIEW_TaskChain.gRecUserUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String grecuseruid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.VIEW_TaskChain.dRecTime
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Date drectime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.VIEW_TaskChain.taskcCompleteTime
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Date taskccompletetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.VIEW_TaskChain.bIsOver
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Boolean bisover;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.VIEW_TaskChain.todGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String todgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.VIEW_TaskChain.gBillTypeUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String gbilltypeuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.VIEW_TaskChain.cBillCode
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String cbillcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.VIEW_TaskChain.gBillUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String gbilluid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.VIEW_TaskChain.ttUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String ttuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.VIEW_TaskChain.cTypeName
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String ctypename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.VIEW_TaskChain.cTypeCode
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String ctypecode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.VIEW_TaskChain.taskGid
     *
     * @return the value of dbo.VIEW_TaskChain.taskGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getTaskgid() {
        return taskgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.VIEW_TaskChain.taskGid
     *
     * @param taskgid the value for dbo.VIEW_TaskChain.taskGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setTaskgid(String taskgid) {
        this.taskgid = taskgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.VIEW_TaskChain.cTaskName
     *
     * @return the value of dbo.VIEW_TaskChain.cTaskName
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getCtaskname() {
        return ctaskname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.VIEW_TaskChain.cTaskName
     *
     * @param ctaskname the value for dbo.VIEW_TaskChain.cTaskName
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setCtaskname(String ctaskname) {
        this.ctaskname = ctaskname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.VIEW_TaskChain.fromgTaskCuid
     *
     * @return the value of dbo.VIEW_TaskChain.fromgTaskCuid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getFromgtaskcuid() {
        return fromgtaskcuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.VIEW_TaskChain.fromgTaskCuid
     *
     * @param fromgtaskcuid the value for dbo.VIEW_TaskChain.fromgTaskCuid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setFromgtaskcuid(String fromgtaskcuid) {
        this.fromgtaskcuid = fromgtaskcuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.VIEW_TaskChain.iState
     *
     * @return the value of dbo.VIEW_TaskChain.iState
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Integer getIstate() {
        return istate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.VIEW_TaskChain.iState
     *
     * @param istate the value for dbo.VIEW_TaskChain.iState
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setIstate(Integer istate) {
        this.istate = istate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.VIEW_TaskChain.bLocked
     *
     * @return the value of dbo.VIEW_TaskChain.bLocked
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Boolean getBlocked() {
        return blocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.VIEW_TaskChain.bLocked
     *
     * @param blocked the value for dbo.VIEW_TaskChain.bLocked
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setBlocked(Boolean blocked) {
        this.blocked = blocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.VIEW_TaskChain.taskCompleteTime
     *
     * @return the value of dbo.VIEW_TaskChain.taskCompleteTime
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Date getTaskcompletetime() {
        return taskcompletetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.VIEW_TaskChain.taskCompleteTime
     *
     * @param taskcompletetime the value for dbo.VIEW_TaskChain.taskCompleteTime
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setTaskcompletetime(Date taskcompletetime) {
        this.taskcompletetime = taskcompletetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.VIEW_TaskChain.taskCGid
     *
     * @return the value of dbo.VIEW_TaskChain.taskCGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getTaskcgid() {
        return taskcgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.VIEW_TaskChain.taskCGid
     *
     * @param taskcgid the value for dbo.VIEW_TaskChain.taskCGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setTaskcgid(String taskcgid) {
        this.taskcgid = taskcgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.VIEW_TaskChain.dDistributeTime
     *
     * @return the value of dbo.VIEW_TaskChain.dDistributeTime
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Date getDdistributetime() {
        return ddistributetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.VIEW_TaskChain.dDistributeTime
     *
     * @param ddistributetime the value for dbo.VIEW_TaskChain.dDistributeTime
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setDdistributetime(Date ddistributetime) {
        this.ddistributetime = ddistributetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.VIEW_TaskChain.dShouldCpltTime
     *
     * @return the value of dbo.VIEW_TaskChain.dShouldCpltTime
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Date getDshouldcplttime() {
        return dshouldcplttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.VIEW_TaskChain.dShouldCpltTime
     *
     * @param dshouldcplttime the value for dbo.VIEW_TaskChain.dShouldCpltTime
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setDshouldcplttime(Date dshouldcplttime) {
        this.dshouldcplttime = dshouldcplttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.VIEW_TaskChain.gAptRecDeptuid
     *
     * @return the value of dbo.VIEW_TaskChain.gAptRecDeptuid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getGaptrecdeptuid() {
        return gaptrecdeptuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.VIEW_TaskChain.gAptRecDeptuid
     *
     * @param gaptrecdeptuid the value for dbo.VIEW_TaskChain.gAptRecDeptuid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setGaptrecdeptuid(String gaptrecdeptuid) {
        this.gaptrecdeptuid = gaptrecdeptuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.VIEW_TaskChain.gAptRecRoleUid
     *
     * @return the value of dbo.VIEW_TaskChain.gAptRecRoleUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getGaptrecroleuid() {
        return gaptrecroleuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.VIEW_TaskChain.gAptRecRoleUid
     *
     * @param gaptrecroleuid the value for dbo.VIEW_TaskChain.gAptRecRoleUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setGaptrecroleuid(String gaptrecroleuid) {
        this.gaptrecroleuid = gaptrecroleuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.VIEW_TaskChain.gAptRecUserUid
     *
     * @return the value of dbo.VIEW_TaskChain.gAptRecUserUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getGaptrecuseruid() {
        return gaptrecuseruid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.VIEW_TaskChain.gAptRecUserUid
     *
     * @param gaptrecuseruid the value for dbo.VIEW_TaskChain.gAptRecUserUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setGaptrecuseruid(String gaptrecuseruid) {
        this.gaptrecuseruid = gaptrecuseruid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.VIEW_TaskChain.gRecUserUid
     *
     * @return the value of dbo.VIEW_TaskChain.gRecUserUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getGrecuseruid() {
        return grecuseruid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.VIEW_TaskChain.gRecUserUid
     *
     * @param grecuseruid the value for dbo.VIEW_TaskChain.gRecUserUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setGrecuseruid(String grecuseruid) {
        this.grecuseruid = grecuseruid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.VIEW_TaskChain.dRecTime
     *
     * @return the value of dbo.VIEW_TaskChain.dRecTime
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Date getDrectime() {
        return drectime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.VIEW_TaskChain.dRecTime
     *
     * @param drectime the value for dbo.VIEW_TaskChain.dRecTime
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setDrectime(Date drectime) {
        this.drectime = drectime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.VIEW_TaskChain.taskcCompleteTime
     *
     * @return the value of dbo.VIEW_TaskChain.taskcCompleteTime
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Date getTaskccompletetime() {
        return taskccompletetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.VIEW_TaskChain.taskcCompleteTime
     *
     * @param taskccompletetime the value for dbo.VIEW_TaskChain.taskcCompleteTime
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setTaskccompletetime(Date taskccompletetime) {
        this.taskccompletetime = taskccompletetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.VIEW_TaskChain.bIsOver
     *
     * @return the value of dbo.VIEW_TaskChain.bIsOver
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Boolean getBisover() {
        return bisover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.VIEW_TaskChain.bIsOver
     *
     * @param bisover the value for dbo.VIEW_TaskChain.bIsOver
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setBisover(Boolean bisover) {
        this.bisover = bisover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.VIEW_TaskChain.todGid
     *
     * @return the value of dbo.VIEW_TaskChain.todGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getTodgid() {
        return todgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.VIEW_TaskChain.todGid
     *
     * @param todgid the value for dbo.VIEW_TaskChain.todGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setTodgid(String todgid) {
        this.todgid = todgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.VIEW_TaskChain.gBillTypeUid
     *
     * @return the value of dbo.VIEW_TaskChain.gBillTypeUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getGbilltypeuid() {
        return gbilltypeuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.VIEW_TaskChain.gBillTypeUid
     *
     * @param gbilltypeuid the value for dbo.VIEW_TaskChain.gBillTypeUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setGbilltypeuid(String gbilltypeuid) {
        this.gbilltypeuid = gbilltypeuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.VIEW_TaskChain.cBillCode
     *
     * @return the value of dbo.VIEW_TaskChain.cBillCode
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getCbillcode() {
        return cbillcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.VIEW_TaskChain.cBillCode
     *
     * @param cbillcode the value for dbo.VIEW_TaskChain.cBillCode
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setCbillcode(String cbillcode) {
        this.cbillcode = cbillcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.VIEW_TaskChain.gBillUid
     *
     * @return the value of dbo.VIEW_TaskChain.gBillUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getGbilluid() {
        return gbilluid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.VIEW_TaskChain.gBillUid
     *
     * @param gbilluid the value for dbo.VIEW_TaskChain.gBillUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setGbilluid(String gbilluid) {
        this.gbilluid = gbilluid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.VIEW_TaskChain.ttUid
     *
     * @return the value of dbo.VIEW_TaskChain.ttUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getTtuid() {
        return ttuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.VIEW_TaskChain.ttUid
     *
     * @param ttuid the value for dbo.VIEW_TaskChain.ttUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setTtuid(String ttuid) {
        this.ttuid = ttuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.VIEW_TaskChain.cTypeName
     *
     * @return the value of dbo.VIEW_TaskChain.cTypeName
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getCtypename() {
        return ctypename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.VIEW_TaskChain.cTypeName
     *
     * @param ctypename the value for dbo.VIEW_TaskChain.cTypeName
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setCtypename(String ctypename) {
        this.ctypename = ctypename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.VIEW_TaskChain.cTypeCode
     *
     * @return the value of dbo.VIEW_TaskChain.cTypeCode
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getCtypecode() {
        return ctypecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.VIEW_TaskChain.cTypeCode
     *
     * @param ctypecode the value for dbo.VIEW_TaskChain.cTypeCode
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setCtypecode(String ctypecode) {
        this.ctypecode = ctypecode;
    }
}