package com.emi.wms.bean;

import java.util.Date;

public class ViewPerson {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.VIEW_PERSON.perGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String pergid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.VIEW_PERSON.cPerCode
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String cpercode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.VIEW_PERSON.cPerName
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String cpername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.VIEW_PERSON.bPerSex
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Boolean bpersex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.VIEW_PERSON.dPerBirthday
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Date dperbirthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.VIEW_PERSON.userGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String usergid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.VIEW_PERSON.cUserCode
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String cusercode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.VIEW_PERSON.cUserName
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String cusername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.VIEW_PERSON.cPassWord
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String cpassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.VIEW_PERSON.bPause
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Boolean bpause;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.VIEW_PERSON.perGid
     *
     * @return the value of dbo.VIEW_PERSON.perGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getPergid() {
        return pergid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.VIEW_PERSON.perGid
     *
     * @param pergid the value for dbo.VIEW_PERSON.perGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setPergid(String pergid) {
        this.pergid = pergid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.VIEW_PERSON.cPerCode
     *
     * @return the value of dbo.VIEW_PERSON.cPerCode
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getCpercode() {
        return cpercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.VIEW_PERSON.cPerCode
     *
     * @param cpercode the value for dbo.VIEW_PERSON.cPerCode
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setCpercode(String cpercode) {
        this.cpercode = cpercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.VIEW_PERSON.cPerName
     *
     * @return the value of dbo.VIEW_PERSON.cPerName
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getCpername() {
        return cpername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.VIEW_PERSON.cPerName
     *
     * @param cpername the value for dbo.VIEW_PERSON.cPerName
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setCpername(String cpername) {
        this.cpername = cpername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.VIEW_PERSON.bPerSex
     *
     * @return the value of dbo.VIEW_PERSON.bPerSex
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Boolean getBpersex() {
        return bpersex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.VIEW_PERSON.bPerSex
     *
     * @param bpersex the value for dbo.VIEW_PERSON.bPerSex
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setBpersex(Boolean bpersex) {
        this.bpersex = bpersex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.VIEW_PERSON.dPerBirthday
     *
     * @return the value of dbo.VIEW_PERSON.dPerBirthday
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Date getDperbirthday() {
        return dperbirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.VIEW_PERSON.dPerBirthday
     *
     * @param dperbirthday the value for dbo.VIEW_PERSON.dPerBirthday
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setDperbirthday(Date dperbirthday) {
        this.dperbirthday = dperbirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.VIEW_PERSON.userGid
     *
     * @return the value of dbo.VIEW_PERSON.userGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getUsergid() {
        return usergid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.VIEW_PERSON.userGid
     *
     * @param usergid the value for dbo.VIEW_PERSON.userGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setUsergid(String usergid) {
        this.usergid = usergid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.VIEW_PERSON.cUserCode
     *
     * @return the value of dbo.VIEW_PERSON.cUserCode
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getCusercode() {
        return cusercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.VIEW_PERSON.cUserCode
     *
     * @param cusercode the value for dbo.VIEW_PERSON.cUserCode
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setCusercode(String cusercode) {
        this.cusercode = cusercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.VIEW_PERSON.cUserName
     *
     * @return the value of dbo.VIEW_PERSON.cUserName
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getCusername() {
        return cusername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.VIEW_PERSON.cUserName
     *
     * @param cusername the value for dbo.VIEW_PERSON.cUserName
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setCusername(String cusername) {
        this.cusername = cusername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.VIEW_PERSON.cPassWord
     *
     * @return the value of dbo.VIEW_PERSON.cPassWord
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getCpassword() {
        return cpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.VIEW_PERSON.cPassWord
     *
     * @param cpassword the value for dbo.VIEW_PERSON.cPassWord
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setCpassword(String cpassword) {
        this.cpassword = cpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.VIEW_PERSON.bPause
     *
     * @return the value of dbo.VIEW_PERSON.bPause
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Boolean getBpause() {
        return bpause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.VIEW_PERSON.bPause
     *
     * @param bpause the value for dbo.VIEW_PERSON.bPause
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setBpause(Boolean bpause) {
        this.bpause = bpause;
    }
}