package com.emi.wms.bean;

import java.math.BigDecimal;

public class ViewPoingoods {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.VIEW_POINGOODS.id
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.VIEW_POINGOODS.cid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    private Integer cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.VIEW_POINGOODS.cgId
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    private String cgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.VIEW_POINGOODS.gId
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    private String gid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.VIEW_POINGOODS.cPoWhUid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    private String cpowhuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.VIEW_POINGOODS.cMaterialUid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    private String cmaterialuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.VIEW_POINGOODS.nQuantity
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    private BigDecimal nquantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.VIEW_POINGOODS.nPrice
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    private BigDecimal nprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.VIEW_POINGOODS.nAmount
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    private BigDecimal namount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.VIEW_POINGOODS.gPoCUid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    private String gpocuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.VIEW_POINGOODS.gPoArrivalCUid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    private String gpoarrivalcuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.VIEW_POINGOODS.cPoWhCUid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    private String cpowhcuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.VIEW_POINGOODS.gMaterialUid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    private String gmaterialuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.VIEW_POINGOODS.nQuantityA
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    private BigDecimal nquantitya;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.VIEW_POINGOODS.gGoodsAllocationUid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    private String ggoodsallocationuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.VIEW_POINGOODS.cGoodsCode
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    private String cgoodscode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.VIEW_POINGOODS.cGoodsName
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    private String cgoodsname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.VIEW_POINGOODS.cGoodsStandard
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    private String cgoodsstandard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.VIEW_POINGOODS.cGoodsUnit
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    private String cgoodsunit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.VIEW_POINGOODS.cGoodsBarCode
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    private String cgoodsbarcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.VIEW_POINGOODS.iScanQuantity
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    private Integer iscanquantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.VIEW_POINGOODS.cAllocationBarCode
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    private String callocationbarcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.VIEW_POINGOODS.cName
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    private String cname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.VIEW_POINGOODS.iShowOrder
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    private Integer ishoworder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.VIEW_POINGOODS.ymts
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    private byte[] ymts;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.VIEW_POINGOODS.id
     *
     * @return the value of dbo.VIEW_POINGOODS.id
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.VIEW_POINGOODS.id
     *
     * @param id the value for dbo.VIEW_POINGOODS.id
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.VIEW_POINGOODS.cid
     *
     * @return the value of dbo.VIEW_POINGOODS.cid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.VIEW_POINGOODS.cid
     *
     * @param cid the value for dbo.VIEW_POINGOODS.cid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.VIEW_POINGOODS.cgId
     *
     * @return the value of dbo.VIEW_POINGOODS.cgId
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public String getCgid() {
        return cgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.VIEW_POINGOODS.cgId
     *
     * @param cgid the value for dbo.VIEW_POINGOODS.cgId
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setCgid(String cgid) {
        this.cgid = cgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.VIEW_POINGOODS.gId
     *
     * @return the value of dbo.VIEW_POINGOODS.gId
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public String getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.VIEW_POINGOODS.gId
     *
     * @param gid the value for dbo.VIEW_POINGOODS.gId
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setGid(String gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.VIEW_POINGOODS.cPoWhUid
     *
     * @return the value of dbo.VIEW_POINGOODS.cPoWhUid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public String getCpowhuid() {
        return cpowhuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.VIEW_POINGOODS.cPoWhUid
     *
     * @param cpowhuid the value for dbo.VIEW_POINGOODS.cPoWhUid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setCpowhuid(String cpowhuid) {
        this.cpowhuid = cpowhuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.VIEW_POINGOODS.cMaterialUid
     *
     * @return the value of dbo.VIEW_POINGOODS.cMaterialUid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public String getCmaterialuid() {
        return cmaterialuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.VIEW_POINGOODS.cMaterialUid
     *
     * @param cmaterialuid the value for dbo.VIEW_POINGOODS.cMaterialUid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setCmaterialuid(String cmaterialuid) {
        this.cmaterialuid = cmaterialuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.VIEW_POINGOODS.nQuantity
     *
     * @return the value of dbo.VIEW_POINGOODS.nQuantity
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public BigDecimal getNquantity() {
        return nquantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.VIEW_POINGOODS.nQuantity
     *
     * @param nquantity the value for dbo.VIEW_POINGOODS.nQuantity
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setNquantity(BigDecimal nquantity) {
        this.nquantity = nquantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.VIEW_POINGOODS.nPrice
     *
     * @return the value of dbo.VIEW_POINGOODS.nPrice
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public BigDecimal getNprice() {
        return nprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.VIEW_POINGOODS.nPrice
     *
     * @param nprice the value for dbo.VIEW_POINGOODS.nPrice
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setNprice(BigDecimal nprice) {
        this.nprice = nprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.VIEW_POINGOODS.nAmount
     *
     * @return the value of dbo.VIEW_POINGOODS.nAmount
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public BigDecimal getNamount() {
        return namount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.VIEW_POINGOODS.nAmount
     *
     * @param namount the value for dbo.VIEW_POINGOODS.nAmount
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setNamount(BigDecimal namount) {
        this.namount = namount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.VIEW_POINGOODS.gPoCUid
     *
     * @return the value of dbo.VIEW_POINGOODS.gPoCUid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public String getGpocuid() {
        return gpocuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.VIEW_POINGOODS.gPoCUid
     *
     * @param gpocuid the value for dbo.VIEW_POINGOODS.gPoCUid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setGpocuid(String gpocuid) {
        this.gpocuid = gpocuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.VIEW_POINGOODS.gPoArrivalCUid
     *
     * @return the value of dbo.VIEW_POINGOODS.gPoArrivalCUid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public String getGpoarrivalcuid() {
        return gpoarrivalcuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.VIEW_POINGOODS.gPoArrivalCUid
     *
     * @param gpoarrivalcuid the value for dbo.VIEW_POINGOODS.gPoArrivalCUid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setGpoarrivalcuid(String gpoarrivalcuid) {
        this.gpoarrivalcuid = gpoarrivalcuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.VIEW_POINGOODS.cPoWhCUid
     *
     * @return the value of dbo.VIEW_POINGOODS.cPoWhCUid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public String getCpowhcuid() {
        return cpowhcuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.VIEW_POINGOODS.cPoWhCUid
     *
     * @param cpowhcuid the value for dbo.VIEW_POINGOODS.cPoWhCUid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setCpowhcuid(String cpowhcuid) {
        this.cpowhcuid = cpowhcuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.VIEW_POINGOODS.gMaterialUid
     *
     * @return the value of dbo.VIEW_POINGOODS.gMaterialUid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public String getGmaterialuid() {
        return gmaterialuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.VIEW_POINGOODS.gMaterialUid
     *
     * @param gmaterialuid the value for dbo.VIEW_POINGOODS.gMaterialUid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setGmaterialuid(String gmaterialuid) {
        this.gmaterialuid = gmaterialuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.VIEW_POINGOODS.nQuantityA
     *
     * @return the value of dbo.VIEW_POINGOODS.nQuantityA
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public BigDecimal getNquantitya() {
        return nquantitya;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.VIEW_POINGOODS.nQuantityA
     *
     * @param nquantitya the value for dbo.VIEW_POINGOODS.nQuantityA
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setNquantitya(BigDecimal nquantitya) {
        this.nquantitya = nquantitya;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.VIEW_POINGOODS.gGoodsAllocationUid
     *
     * @return the value of dbo.VIEW_POINGOODS.gGoodsAllocationUid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public String getGgoodsallocationuid() {
        return ggoodsallocationuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.VIEW_POINGOODS.gGoodsAllocationUid
     *
     * @param ggoodsallocationuid the value for dbo.VIEW_POINGOODS.gGoodsAllocationUid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setGgoodsallocationuid(String ggoodsallocationuid) {
        this.ggoodsallocationuid = ggoodsallocationuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.VIEW_POINGOODS.cGoodsCode
     *
     * @return the value of dbo.VIEW_POINGOODS.cGoodsCode
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public String getCgoodscode() {
        return cgoodscode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.VIEW_POINGOODS.cGoodsCode
     *
     * @param cgoodscode the value for dbo.VIEW_POINGOODS.cGoodsCode
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setCgoodscode(String cgoodscode) {
        this.cgoodscode = cgoodscode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.VIEW_POINGOODS.cGoodsName
     *
     * @return the value of dbo.VIEW_POINGOODS.cGoodsName
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public String getCgoodsname() {
        return cgoodsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.VIEW_POINGOODS.cGoodsName
     *
     * @param cgoodsname the value for dbo.VIEW_POINGOODS.cGoodsName
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setCgoodsname(String cgoodsname) {
        this.cgoodsname = cgoodsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.VIEW_POINGOODS.cGoodsStandard
     *
     * @return the value of dbo.VIEW_POINGOODS.cGoodsStandard
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public String getCgoodsstandard() {
        return cgoodsstandard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.VIEW_POINGOODS.cGoodsStandard
     *
     * @param cgoodsstandard the value for dbo.VIEW_POINGOODS.cGoodsStandard
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setCgoodsstandard(String cgoodsstandard) {
        this.cgoodsstandard = cgoodsstandard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.VIEW_POINGOODS.cGoodsUnit
     *
     * @return the value of dbo.VIEW_POINGOODS.cGoodsUnit
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public String getCgoodsunit() {
        return cgoodsunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.VIEW_POINGOODS.cGoodsUnit
     *
     * @param cgoodsunit the value for dbo.VIEW_POINGOODS.cGoodsUnit
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setCgoodsunit(String cgoodsunit) {
        this.cgoodsunit = cgoodsunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.VIEW_POINGOODS.cGoodsBarCode
     *
     * @return the value of dbo.VIEW_POINGOODS.cGoodsBarCode
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public String getCgoodsbarcode() {
        return cgoodsbarcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.VIEW_POINGOODS.cGoodsBarCode
     *
     * @param cgoodsbarcode the value for dbo.VIEW_POINGOODS.cGoodsBarCode
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setCgoodsbarcode(String cgoodsbarcode) {
        this.cgoodsbarcode = cgoodsbarcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.VIEW_POINGOODS.iScanQuantity
     *
     * @return the value of dbo.VIEW_POINGOODS.iScanQuantity
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public Integer getIscanquantity() {
        return iscanquantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.VIEW_POINGOODS.iScanQuantity
     *
     * @param iscanquantity the value for dbo.VIEW_POINGOODS.iScanQuantity
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setIscanquantity(Integer iscanquantity) {
        this.iscanquantity = iscanquantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.VIEW_POINGOODS.cAllocationBarCode
     *
     * @return the value of dbo.VIEW_POINGOODS.cAllocationBarCode
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public String getCallocationbarcode() {
        return callocationbarcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.VIEW_POINGOODS.cAllocationBarCode
     *
     * @param callocationbarcode the value for dbo.VIEW_POINGOODS.cAllocationBarCode
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setCallocationbarcode(String callocationbarcode) {
        this.callocationbarcode = callocationbarcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.VIEW_POINGOODS.cName
     *
     * @return the value of dbo.VIEW_POINGOODS.cName
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.VIEW_POINGOODS.cName
     *
     * @param cname the value for dbo.VIEW_POINGOODS.cName
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setCname(String cname) {
        this.cname = cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.VIEW_POINGOODS.iShowOrder
     *
     * @return the value of dbo.VIEW_POINGOODS.iShowOrder
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public Integer getIshoworder() {
        return ishoworder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.VIEW_POINGOODS.iShowOrder
     *
     * @param ishoworder the value for dbo.VIEW_POINGOODS.iShowOrder
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setIshoworder(Integer ishoworder) {
        this.ishoworder = ishoworder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.VIEW_POINGOODS.ymts
     *
     * @return the value of dbo.VIEW_POINGOODS.ymts
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public byte[] getYmts() {
        return ymts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.VIEW_POINGOODS.ymts
     *
     * @param ymts the value for dbo.VIEW_POINGOODS.ymts
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setYmts(byte[] ymts) {
        this.ymts = ymts;
    }
}