package com.emi.wms.bean;

import java.math.BigDecimal;

public class WmCallinC {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_Callin_C.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Integer pk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_Callin_C.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String gid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_Callin_C.notice
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String notice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_Callin_C.callinUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String callinuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_Callin_C.goodsUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String goodsuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_Callin_C.number
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private BigDecimal number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_Callin_C.calloutCuid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String calloutcuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_Callin_C.goodsAllocationUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String goodsallocationuid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_Callin_C.pk
     *
     * @return the value of dbo.WM_Callin_C.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Integer getPk() {
        return pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_Callin_C.pk
     *
     * @param pk the value for dbo.WM_Callin_C.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setPk(Integer pk) {
        this.pk = pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_Callin_C.gid
     *
     * @return the value of dbo.WM_Callin_C.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_Callin_C.gid
     *
     * @param gid the value for dbo.WM_Callin_C.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setGid(String gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_Callin_C.notice
     *
     * @return the value of dbo.WM_Callin_C.notice
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getNotice() {
        return notice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_Callin_C.notice
     *
     * @param notice the value for dbo.WM_Callin_C.notice
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setNotice(String notice) {
        this.notice = notice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_Callin_C.callinUid
     *
     * @return the value of dbo.WM_Callin_C.callinUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getCallinuid() {
        return callinuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_Callin_C.callinUid
     *
     * @param callinuid the value for dbo.WM_Callin_C.callinUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setCallinuid(String callinuid) {
        this.callinuid = callinuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_Callin_C.goodsUid
     *
     * @return the value of dbo.WM_Callin_C.goodsUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getGoodsuid() {
        return goodsuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_Callin_C.goodsUid
     *
     * @param goodsuid the value for dbo.WM_Callin_C.goodsUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setGoodsuid(String goodsuid) {
        this.goodsuid = goodsuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_Callin_C.number
     *
     * @return the value of dbo.WM_Callin_C.number
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public BigDecimal getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_Callin_C.number
     *
     * @param number the value for dbo.WM_Callin_C.number
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setNumber(BigDecimal number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_Callin_C.calloutCuid
     *
     * @return the value of dbo.WM_Callin_C.calloutCuid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getCalloutcuid() {
        return calloutcuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_Callin_C.calloutCuid
     *
     * @param calloutcuid the value for dbo.WM_Callin_C.calloutCuid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setCalloutcuid(String calloutcuid) {
        this.calloutcuid = calloutcuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_Callin_C.goodsAllocationUid
     *
     * @return the value of dbo.WM_Callin_C.goodsAllocationUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getGoodsallocationuid() {
        return goodsallocationuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_Callin_C.goodsAllocationUid
     *
     * @param goodsallocationuid the value for dbo.WM_Callin_C.goodsAllocationUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setGoodsallocationuid(String goodsallocationuid) {
        this.goodsallocationuid = goodsallocationuid;
    }
}