package com.emi.wms.bean;

import java.math.BigDecimal;

public class WmCalloutC {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_Callout_C.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Integer pk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_Callout_C.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String gid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_Callout_C.notes
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String notes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_Callout_C.calloutUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String calloutuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_Callout_C.goodsUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String goodsuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_Callout_C.number
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private BigDecimal number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_Callout_C.putinNum
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private BigDecimal putinnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_Callout_C.goodsAllocationUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String goodsallocationuid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_Callout_C.pk
     *
     * @return the value of dbo.WM_Callout_C.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Integer getPk() {
        return pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_Callout_C.pk
     *
     * @param pk the value for dbo.WM_Callout_C.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setPk(Integer pk) {
        this.pk = pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_Callout_C.gid
     *
     * @return the value of dbo.WM_Callout_C.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_Callout_C.gid
     *
     * @param gid the value for dbo.WM_Callout_C.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setGid(String gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_Callout_C.notes
     *
     * @return the value of dbo.WM_Callout_C.notes
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_Callout_C.notes
     *
     * @param notes the value for dbo.WM_Callout_C.notes
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setNotes(String notes) {
        this.notes = notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_Callout_C.calloutUid
     *
     * @return the value of dbo.WM_Callout_C.calloutUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getCalloutuid() {
        return calloutuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_Callout_C.calloutUid
     *
     * @param calloutuid the value for dbo.WM_Callout_C.calloutUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setCalloutuid(String calloutuid) {
        this.calloutuid = calloutuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_Callout_C.goodsUid
     *
     * @return the value of dbo.WM_Callout_C.goodsUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getGoodsuid() {
        return goodsuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_Callout_C.goodsUid
     *
     * @param goodsuid the value for dbo.WM_Callout_C.goodsUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setGoodsuid(String goodsuid) {
        this.goodsuid = goodsuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_Callout_C.number
     *
     * @return the value of dbo.WM_Callout_C.number
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public BigDecimal getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_Callout_C.number
     *
     * @param number the value for dbo.WM_Callout_C.number
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setNumber(BigDecimal number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_Callout_C.putinNum
     *
     * @return the value of dbo.WM_Callout_C.putinNum
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public BigDecimal getPutinnum() {
        return putinnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_Callout_C.putinNum
     *
     * @param putinnum the value for dbo.WM_Callout_C.putinNum
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setPutinnum(BigDecimal putinnum) {
        this.putinnum = putinnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_Callout_C.goodsAllocationUid
     *
     * @return the value of dbo.WM_Callout_C.goodsAllocationUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getGoodsallocationuid() {
        return goodsallocationuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_Callout_C.goodsAllocationUid
     *
     * @param goodsallocationuid the value for dbo.WM_Callout_C.goodsAllocationUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setGoodsallocationuid(String goodsallocationuid) {
        this.goodsallocationuid = goodsallocationuid;
    }
}