package com.emi.wms.bean;

import java.math.BigDecimal;
import java.util.Date;

public class WmPaymentorder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_PaymentOrder.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Integer pk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_PaymentOrder.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String gid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_PaymentOrder.billCode
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String billcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_PaymentOrder.billDate
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Date billdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_PaymentOrder.currency
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String currency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_PaymentOrder.providerUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String provideruid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_PaymentOrder.settlementMethod
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String settlementmethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_PaymentOrder.departmentUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String departmentuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_PaymentOrder.personUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String personuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_PaymentOrder.notes
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String notes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_PaymentOrder.amount
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_PaymentOrder.recordPersonUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String recordpersonuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_PaymentOrder.recordDate
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Date recorddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_PaymentOrder.auditPersonUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String auditpersonuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_PaymentOrder.auditDate
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Date auditdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_PaymentOrder.sobGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String sobgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_PaymentOrder.orgGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String orggid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_PaymentOrder.flag
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Integer flag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_PaymentOrder.pk
     *
     * @return the value of dbo.WM_PaymentOrder.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Integer getPk() {
        return pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_PaymentOrder.pk
     *
     * @param pk the value for dbo.WM_PaymentOrder.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setPk(Integer pk) {
        this.pk = pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_PaymentOrder.gid
     *
     * @return the value of dbo.WM_PaymentOrder.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_PaymentOrder.gid
     *
     * @param gid the value for dbo.WM_PaymentOrder.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setGid(String gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_PaymentOrder.billCode
     *
     * @return the value of dbo.WM_PaymentOrder.billCode
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getBillcode() {
        return billcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_PaymentOrder.billCode
     *
     * @param billcode the value for dbo.WM_PaymentOrder.billCode
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setBillcode(String billcode) {
        this.billcode = billcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_PaymentOrder.billDate
     *
     * @return the value of dbo.WM_PaymentOrder.billDate
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Date getBilldate() {
        return billdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_PaymentOrder.billDate
     *
     * @param billdate the value for dbo.WM_PaymentOrder.billDate
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setBilldate(Date billdate) {
        this.billdate = billdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_PaymentOrder.currency
     *
     * @return the value of dbo.WM_PaymentOrder.currency
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_PaymentOrder.currency
     *
     * @param currency the value for dbo.WM_PaymentOrder.currency
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setCurrency(String currency) {
        this.currency = currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_PaymentOrder.providerUid
     *
     * @return the value of dbo.WM_PaymentOrder.providerUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getProvideruid() {
        return provideruid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_PaymentOrder.providerUid
     *
     * @param provideruid the value for dbo.WM_PaymentOrder.providerUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setProvideruid(String provideruid) {
        this.provideruid = provideruid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_PaymentOrder.settlementMethod
     *
     * @return the value of dbo.WM_PaymentOrder.settlementMethod
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getSettlementmethod() {
        return settlementmethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_PaymentOrder.settlementMethod
     *
     * @param settlementmethod the value for dbo.WM_PaymentOrder.settlementMethod
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setSettlementmethod(String settlementmethod) {
        this.settlementmethod = settlementmethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_PaymentOrder.departmentUid
     *
     * @return the value of dbo.WM_PaymentOrder.departmentUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getDepartmentuid() {
        return departmentuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_PaymentOrder.departmentUid
     *
     * @param departmentuid the value for dbo.WM_PaymentOrder.departmentUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setDepartmentuid(String departmentuid) {
        this.departmentuid = departmentuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_PaymentOrder.personUid
     *
     * @return the value of dbo.WM_PaymentOrder.personUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getPersonuid() {
        return personuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_PaymentOrder.personUid
     *
     * @param personuid the value for dbo.WM_PaymentOrder.personUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setPersonuid(String personuid) {
        this.personuid = personuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_PaymentOrder.notes
     *
     * @return the value of dbo.WM_PaymentOrder.notes
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_PaymentOrder.notes
     *
     * @param notes the value for dbo.WM_PaymentOrder.notes
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setNotes(String notes) {
        this.notes = notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_PaymentOrder.amount
     *
     * @return the value of dbo.WM_PaymentOrder.amount
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_PaymentOrder.amount
     *
     * @param amount the value for dbo.WM_PaymentOrder.amount
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_PaymentOrder.recordPersonUid
     *
     * @return the value of dbo.WM_PaymentOrder.recordPersonUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getRecordpersonuid() {
        return recordpersonuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_PaymentOrder.recordPersonUid
     *
     * @param recordpersonuid the value for dbo.WM_PaymentOrder.recordPersonUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setRecordpersonuid(String recordpersonuid) {
        this.recordpersonuid = recordpersonuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_PaymentOrder.recordDate
     *
     * @return the value of dbo.WM_PaymentOrder.recordDate
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Date getRecorddate() {
        return recorddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_PaymentOrder.recordDate
     *
     * @param recorddate the value for dbo.WM_PaymentOrder.recordDate
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setRecorddate(Date recorddate) {
        this.recorddate = recorddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_PaymentOrder.auditPersonUid
     *
     * @return the value of dbo.WM_PaymentOrder.auditPersonUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getAuditpersonuid() {
        return auditpersonuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_PaymentOrder.auditPersonUid
     *
     * @param auditpersonuid the value for dbo.WM_PaymentOrder.auditPersonUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setAuditpersonuid(String auditpersonuid) {
        this.auditpersonuid = auditpersonuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_PaymentOrder.auditDate
     *
     * @return the value of dbo.WM_PaymentOrder.auditDate
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Date getAuditdate() {
        return auditdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_PaymentOrder.auditDate
     *
     * @param auditdate the value for dbo.WM_PaymentOrder.auditDate
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setAuditdate(Date auditdate) {
        this.auditdate = auditdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_PaymentOrder.sobGid
     *
     * @return the value of dbo.WM_PaymentOrder.sobGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getSobgid() {
        return sobgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_PaymentOrder.sobGid
     *
     * @param sobgid the value for dbo.WM_PaymentOrder.sobGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setSobgid(String sobgid) {
        this.sobgid = sobgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_PaymentOrder.orgGid
     *
     * @return the value of dbo.WM_PaymentOrder.orgGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getOrggid() {
        return orggid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_PaymentOrder.orgGid
     *
     * @param orggid the value for dbo.WM_PaymentOrder.orgGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setOrggid(String orggid) {
        this.orggid = orggid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_PaymentOrder.flag
     *
     * @return the value of dbo.WM_PaymentOrder.flag
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_PaymentOrder.flag
     *
     * @param flag the value for dbo.WM_PaymentOrder.flag
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }
}