package com.emi.wms.bean;

import java.math.BigDecimal;
import java.util.Date;

public class WmPaymentorderC {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_PaymentOrder_C.pk
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    private Integer pk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_PaymentOrder_C.gid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    private String gid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_PaymentOrder_C.paymentOrderUid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    private String paymentorderuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_PaymentOrder_C.goodsUid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    private String goodsuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_PaymentOrder_C.number
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    private BigDecimal number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_PaymentOrder_C.paymentAmount
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    private BigDecimal paymentamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_PaymentOrder_C.amount
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_PaymentOrder_C.verificationDate
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    private Date verificationdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_PaymentOrder_C.pk
     *
     * @return the value of dbo.WM_PaymentOrder_C.pk
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public Integer getPk() {
        return pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_PaymentOrder_C.pk
     *
     * @param pk the value for dbo.WM_PaymentOrder_C.pk
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setPk(Integer pk) {
        this.pk = pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_PaymentOrder_C.gid
     *
     * @return the value of dbo.WM_PaymentOrder_C.gid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public String getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_PaymentOrder_C.gid
     *
     * @param gid the value for dbo.WM_PaymentOrder_C.gid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setGid(String gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_PaymentOrder_C.paymentOrderUid
     *
     * @return the value of dbo.WM_PaymentOrder_C.paymentOrderUid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public String getPaymentorderuid() {
        return paymentorderuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_PaymentOrder_C.paymentOrderUid
     *
     * @param paymentorderuid the value for dbo.WM_PaymentOrder_C.paymentOrderUid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setPaymentorderuid(String paymentorderuid) {
        this.paymentorderuid = paymentorderuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_PaymentOrder_C.goodsUid
     *
     * @return the value of dbo.WM_PaymentOrder_C.goodsUid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public String getGoodsuid() {
        return goodsuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_PaymentOrder_C.goodsUid
     *
     * @param goodsuid the value for dbo.WM_PaymentOrder_C.goodsUid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setGoodsuid(String goodsuid) {
        this.goodsuid = goodsuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_PaymentOrder_C.number
     *
     * @return the value of dbo.WM_PaymentOrder_C.number
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public BigDecimal getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_PaymentOrder_C.number
     *
     * @param number the value for dbo.WM_PaymentOrder_C.number
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setNumber(BigDecimal number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_PaymentOrder_C.paymentAmount
     *
     * @return the value of dbo.WM_PaymentOrder_C.paymentAmount
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public BigDecimal getPaymentamount() {
        return paymentamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_PaymentOrder_C.paymentAmount
     *
     * @param paymentamount the value for dbo.WM_PaymentOrder_C.paymentAmount
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setPaymentamount(BigDecimal paymentamount) {
        this.paymentamount = paymentamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_PaymentOrder_C.amount
     *
     * @return the value of dbo.WM_PaymentOrder_C.amount
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_PaymentOrder_C.amount
     *
     * @param amount the value for dbo.WM_PaymentOrder_C.amount
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_PaymentOrder_C.verificationDate
     *
     * @return the value of dbo.WM_PaymentOrder_C.verificationDate
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public Date getVerificationdate() {
        return verificationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_PaymentOrder_C.verificationDate
     *
     * @param verificationdate the value for dbo.WM_PaymentOrder_C.verificationDate
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setVerificationdate(Date verificationdate) {
        this.verificationdate = verificationdate;
    }
}