package com.emi.wms.bean;

import java.math.BigDecimal;
import java.util.Date;

import com.emi.sys.core.annotation.EmiColumn;
import com.emi.sys.core.annotation.EmiTable;
@EmiTable(name="WM_ProcureOrder_C")
public class WmProcureorderC {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_ProcureOrder_C.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
	@EmiColumn(name="pk" ,increment=true)
    private Integer pk;

    @EmiColumn(name="autoidForSynchro")
    private String autoidForSynchro;

    public String getAutoidForSynchro() {
        return autoidForSynchro;
    }

    public void setAutoidForSynchro(String autoidForSynchro) {
        this.autoidForSynchro = autoidForSynchro;
    }

    @EmiColumn(name="idForSynchro")
	private String idForSynchro;


    public String getIdForSynchro() {
        return idForSynchro;
    }

    public void setIdForSynchro(String idForSynchro) {
        this.idForSynchro = idForSynchro;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_ProcureOrder_C.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
	@EmiColumn(name = "gid", ID = true)
    private String gid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_ProcureOrder_C.notes
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
	@EmiColumn(name="notes" )
    private String notes;//备注

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_ProcureOrder_C.procureOrderUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
	@EmiColumn(name="procureorderuid" )
    private String procureorderuid;//主表id

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_ProcureOrder_C.goodsUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
	@EmiColumn(name="goodsuid" )
    private String goodsuid;//物料id

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_ProcureOrder_C.number
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
	@EmiColumn(name="number" )
    private BigDecimal number;//主数量

	@EmiColumn(name="amount" )
    private BigDecimal amount;//辅数量
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_ProcureOrder_C.localPrice
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */

    private BigDecimal localprice;//报价

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_ProcureOrder_C.originalTaxPrice
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
	@EmiColumn(name="originaltaxprice" )
    private BigDecimal originaltaxprice;//原币含税单价

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_ProcureOrder_C.originalTaxMoney
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
	@EmiColumn(name="originaltaxmoney" )
    private BigDecimal originaltaxmoney;//原币含税金额

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_ProcureOrder_C.originalNotaxPrice
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
	@EmiColumn(name="originalnotaxprice" )
    private BigDecimal originalnotaxprice;//原币不含税单价

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_ProcureOrder_C.originalNotaxMoney
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
	@EmiColumn(name="originalnotaxmoney" )
    private BigDecimal originalnotaxmoney;//原币不含税金额

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_ProcureOrder_C.originalTax
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
	@EmiColumn(name="originaltax" )
    private BigDecimal originaltax;//原币税额

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_ProcureOrder_C.localTaxPrice
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
	@EmiColumn(name="localtaxprice" )
    private BigDecimal localtaxprice;//本币含税单价

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_ProcureOrder_C.localTaxMoney
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
	@EmiColumn(name="localtaxmoney" )
    private BigDecimal localtaxmoney;//本币含税金额

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_ProcureOrder_C.localNotaxPrice
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
	@EmiColumn(name="localnotaxprice" )
    private BigDecimal localnotaxprice;//本币不含税单价

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_ProcureOrder_C.localNotaxMoney
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
	@EmiColumn(name="localnotaxmoney" )
    private BigDecimal localnotaxmoney;//本币不含税金额

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_ProcureOrder_C.localTax
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
	@EmiColumn(name="localtax" )
    private BigDecimal localtax;//本币税额

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_ProcureOrder_C.receiveNumber
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
	@EmiColumn(name="receivenumber" )
    private BigDecimal receivenumber;//已到货数量

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_ProcureOrder_C.putinNumber
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
	@EmiColumn(name="putinnumber" )
    private BigDecimal putinnumber;//已入库数量

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_ProcureOrder_C.planAOG
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
	@EmiColumn(name="planaog" )
    private Date planaog;//计划到货日

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_ProcureOrder_C.pk
     *
     * @return the value of dbo.WM_ProcureOrder_C.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Integer getPk() {
        return pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_ProcureOrder_C.pk
     *
     * @param pk the value for dbo.WM_ProcureOrder_C.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setPk(Integer pk) {
        this.pk = pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_ProcureOrder_C.gid
     *
     * @return the value of dbo.WM_ProcureOrder_C.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_ProcureOrder_C.gid
     *
     * @param gid the value for dbo.WM_ProcureOrder_C.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setGid(String gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_ProcureOrder_C.notes
     *
     * @return the value of dbo.WM_ProcureOrder_C.notes
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_ProcureOrder_C.notes
     *
     * @param notes the value for dbo.WM_ProcureOrder_C.notes
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setNotes(String notes) {
        this.notes = notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_ProcureOrder_C.procureOrderUid
     *
     * @return the value of dbo.WM_ProcureOrder_C.procureOrderUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getProcureorderuid() {
        return procureorderuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_ProcureOrder_C.procureOrderUid
     *
     * @param procureorderuid the value for dbo.WM_ProcureOrder_C.procureOrderUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setProcureorderuid(String procureorderuid) {
        this.procureorderuid = procureorderuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_ProcureOrder_C.goodsUid
     *
     * @return the value of dbo.WM_ProcureOrder_C.goodsUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getGoodsuid() {
        return goodsuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_ProcureOrder_C.goodsUid
     *
     * @param goodsuid the value for dbo.WM_ProcureOrder_C.goodsUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setGoodsuid(String goodsuid) {
        this.goodsuid = goodsuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_ProcureOrder_C.number
     *
     * @return the value of dbo.WM_ProcureOrder_C.number
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public BigDecimal getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_ProcureOrder_C.number
     *
     * @param number the value for dbo.WM_ProcureOrder_C.number
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setNumber(BigDecimal number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_ProcureOrder_C.localPrice
     *
     * @return the value of dbo.WM_ProcureOrder_C.localPrice
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public BigDecimal getLocalprice() {
        return localprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_ProcureOrder_C.localPrice
     *
     * @param localprice the value for dbo.WM_ProcureOrder_C.localPrice
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setLocalprice(BigDecimal localprice) {
        this.localprice = localprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_ProcureOrder_C.originalTaxPrice
     *
     * @return the value of dbo.WM_ProcureOrder_C.originalTaxPrice
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public BigDecimal getOriginaltaxprice() {
        return originaltaxprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_ProcureOrder_C.originalTaxPrice
     *
     * @param originaltaxprice the value for dbo.WM_ProcureOrder_C.originalTaxPrice
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setOriginaltaxprice(BigDecimal originaltaxprice) {
        this.originaltaxprice = originaltaxprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_ProcureOrder_C.originalTaxMoney
     *
     * @return the value of dbo.WM_ProcureOrder_C.originalTaxMoney
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public BigDecimal getOriginaltaxmoney() {
        return originaltaxmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_ProcureOrder_C.originalTaxMoney
     *
     * @param originaltaxmoney the value for dbo.WM_ProcureOrder_C.originalTaxMoney
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setOriginaltaxmoney(BigDecimal originaltaxmoney) {
        this.originaltaxmoney = originaltaxmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_ProcureOrder_C.originalNotaxPrice
     *
     * @return the value of dbo.WM_ProcureOrder_C.originalNotaxPrice
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public BigDecimal getOriginalnotaxprice() {
        return originalnotaxprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_ProcureOrder_C.originalNotaxPrice
     *
     * @param originalnotaxprice the value for dbo.WM_ProcureOrder_C.originalNotaxPrice
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setOriginalnotaxprice(BigDecimal originalnotaxprice) {
        this.originalnotaxprice = originalnotaxprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_ProcureOrder_C.originalNotaxMoney
     *
     * @return the value of dbo.WM_ProcureOrder_C.originalNotaxMoney
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public BigDecimal getOriginalnotaxmoney() {
        return originalnotaxmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_ProcureOrder_C.originalNotaxMoney
     *
     * @param originalnotaxmoney the value for dbo.WM_ProcureOrder_C.originalNotaxMoney
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setOriginalnotaxmoney(BigDecimal originalnotaxmoney) {
        this.originalnotaxmoney = originalnotaxmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_ProcureOrder_C.originalTax
     *
     * @return the value of dbo.WM_ProcureOrder_C.originalTax
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public BigDecimal getOriginaltax() {
        return originaltax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_ProcureOrder_C.originalTax
     *
     * @param originaltax the value for dbo.WM_ProcureOrder_C.originalTax
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setOriginaltax(BigDecimal originaltax) {
        this.originaltax = originaltax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_ProcureOrder_C.localTaxPrice
     *
     * @return the value of dbo.WM_ProcureOrder_C.localTaxPrice
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public BigDecimal getLocaltaxprice() {
        return localtaxprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_ProcureOrder_C.localTaxPrice
     *
     * @param localtaxprice the value for dbo.WM_ProcureOrder_C.localTaxPrice
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setLocaltaxprice(BigDecimal localtaxprice) {
        this.localtaxprice = localtaxprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_ProcureOrder_C.localTaxMoney
     *
     * @return the value of dbo.WM_ProcureOrder_C.localTaxMoney
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public BigDecimal getLocaltaxmoney() {
        return localtaxmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_ProcureOrder_C.localTaxMoney
     *
     * @param localtaxmoney the value for dbo.WM_ProcureOrder_C.localTaxMoney
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setLocaltaxmoney(BigDecimal localtaxmoney) {
        this.localtaxmoney = localtaxmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_ProcureOrder_C.localNotaxPrice
     *
     * @return the value of dbo.WM_ProcureOrder_C.localNotaxPrice
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public BigDecimal getLocalnotaxprice() {
        return localnotaxprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_ProcureOrder_C.localNotaxPrice
     *
     * @param localnotaxprice the value for dbo.WM_ProcureOrder_C.localNotaxPrice
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setLocalnotaxprice(BigDecimal localnotaxprice) {
        this.localnotaxprice = localnotaxprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_ProcureOrder_C.localNotaxMoney
     *
     * @return the value of dbo.WM_ProcureOrder_C.localNotaxMoney
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public BigDecimal getLocalnotaxmoney() {
        return localnotaxmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_ProcureOrder_C.localNotaxMoney
     *
     * @param localnotaxmoney the value for dbo.WM_ProcureOrder_C.localNotaxMoney
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setLocalnotaxmoney(BigDecimal localnotaxmoney) {
        this.localnotaxmoney = localnotaxmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_ProcureOrder_C.localTax
     *
     * @return the value of dbo.WM_ProcureOrder_C.localTax
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public BigDecimal getLocaltax() {
        return localtax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_ProcureOrder_C.localTax
     *
     * @param localtax the value for dbo.WM_ProcureOrder_C.localTax
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setLocaltax(BigDecimal localtax) {
        this.localtax = localtax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_ProcureOrder_C.receiveNumber
     *
     * @return the value of dbo.WM_ProcureOrder_C.receiveNumber
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public BigDecimal getReceivenumber() {
        return receivenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_ProcureOrder_C.receiveNumber
     *
     * @param receivenumber the value for dbo.WM_ProcureOrder_C.receiveNumber
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setReceivenumber(BigDecimal receivenumber) {
        this.receivenumber = receivenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_ProcureOrder_C.putinNumber
     *
     * @return the value of dbo.WM_ProcureOrder_C.putinNumber
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public BigDecimal getPutinnumber() {
        return putinnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_ProcureOrder_C.putinNumber
     *
     * @param putinnumber the value for dbo.WM_ProcureOrder_C.putinNumber
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setPutinnumber(BigDecimal putinnumber) {
        this.putinnumber = putinnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_ProcureOrder_C.planAOG
     *
     * @return the value of dbo.WM_ProcureOrder_C.planAOG
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Date getPlanaog() {
        return planaog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_ProcureOrder_C.planAOG
     *
     * @param planaog the value for dbo.WM_ProcureOrder_C.planAOG
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setPlanaog(Date planaog) {
        this.planaog = planaog;
    }

	public BigDecimal getAmount() {
		return amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}
    
}