package com.emi.wms.bean;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import com.emi.sys.core.annotation.EmiColumn;
import com.emi.sys.core.annotation.EmiTable;
@EmiTable(name="WM_SaleSend")
public class WmSalesend implements Serializable{

	private static final long serialVersionUID = 8121700123111218777L;

	//pk 
	@EmiColumn(name="pk" ,increment=true)
    private Integer pk;

	//gid 
	@EmiColumn(name = "gid", ID = true)
    private String gid;

	//备注 
	@EmiColumn(name="notes" )
    private String notes;

	//客户uid 
	@EmiColumn(name="customeruid" )
    private String customeruid;

	//销售类型 
	@EmiColumn(name="saletype" )
    private String saletype;

	//币种 
	@EmiColumn(name="currency" )
    private String currency;

	//汇率 
	@EmiColumn(name="exchangerate" )
    private BigDecimal exchangerate;

	//税率
	@EmiColumn(name="rate" )
    private BigDecimal rate;

	//运输方式
	@EmiColumn(name="transportation" )
    private String transportation;

	//单据号 
	@EmiColumn(name="billcode" )
    private String billcode;

	//单据状态 
	@EmiColumn(name="billstate" )
    private String billstate;

	//单据日期 
	@EmiColumn(name="billdate" )
    private Date billdate;

	//录入人 
	@EmiColumn(name="recordpersonuid" )
    private String recordpersonuid;

	//录入日期 
	@EmiColumn(name="recorddate" )
    private Date recorddate;

	//录入时间
	@EmiColumn(name="recordtime" )
    private Date recordtime;

	//审核人 
	@EmiColumn(name="auditpersonuid" )
    private String auditpersonuid;

	//审核日期 
	@EmiColumn(name="auditdate" )
    private Date auditdate;

	//审核时间 
	@EmiColumn(name="audittime" )
    private Date audittime;

	//条码 
	@EmiColumn(name="barcode" )
    private String barcode;

	//仓库uid 
	/*@EmiColumn(name="whuid" )
    private String whuid;*/

	//是否退库 
	@EmiColumn(name="isreturn" )
    private Integer isreturn;

	//是否打包 
	/*@EmiColumn(name="ispack" )
    private Integer ispack;*/

	//允许运输的方式 
	@EmiColumn(name="transport" )
    private String transport;

	//帐套ID
	@EmiColumn(name="sobgid" )
    private String sobgid;

	//组织id
	@EmiColumn(name="orggid" )
    private String orggid;

	//删除状态
	@EmiColumn(name="isdel")
    private Integer isdel;    
	
	@EmiColumn(name="define1")
	private String define1;//自定义项1 是否质检
	
	
	
	
	
    public String getDefine1() {
		return define1;
	}

	public void setDefine1(String define1) {
		this.define1 = define1;
	}

	public Integer getPk() {
        return pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_SaleSend.pk
     *
     * @param pk the value for dbo.WM_SaleSend.pk
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setPk(Integer pk) {
        this.pk = pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_SaleSend.gid
     *
     * @return the value of dbo.WM_SaleSend.gid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public String getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_SaleSend.gid
     *
     * @param gid the value for dbo.WM_SaleSend.gid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setGid(String gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_SaleSend.notes
     *
     * @return the value of dbo.WM_SaleSend.notes
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_SaleSend.notes
     *
     * @param notes the value for dbo.WM_SaleSend.notes
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setNotes(String notes) {
        this.notes = notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_SaleSend.customerUid
     *
     * @return the value of dbo.WM_SaleSend.customerUid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public String getCustomeruid() {
        return customeruid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_SaleSend.customerUid
     *
     * @param customeruid the value for dbo.WM_SaleSend.customerUid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setCustomeruid(String customeruid) {
        this.customeruid = customeruid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_SaleSend.saleType
     *
     * @return the value of dbo.WM_SaleSend.saleType
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public String getSaletype() {
        return saletype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_SaleSend.saleType
     *
     * @param saletype the value for dbo.WM_SaleSend.saleType
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setSaletype(String saletype) {
        this.saletype = saletype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_SaleSend.currency
     *
     * @return the value of dbo.WM_SaleSend.currency
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_SaleSend.currency
     *
     * @param currency the value for dbo.WM_SaleSend.currency
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setCurrency(String currency) {
        this.currency = currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_SaleSend.exchangerate
     *
     * @return the value of dbo.WM_SaleSend.exchangerate
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public BigDecimal getExchangerate() {
        return exchangerate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_SaleSend.exchangerate
     *
     * @param exchangerate the value for dbo.WM_SaleSend.exchangerate
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setExchangerate(BigDecimal exchangerate) {
        this.exchangerate = exchangerate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_SaleSend.rate
     *
     * @return the value of dbo.WM_SaleSend.rate
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public BigDecimal getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_SaleSend.rate
     *
     * @param rate the value for dbo.WM_SaleSend.rate
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setRate(BigDecimal rate) {
        this.rate = rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_SaleSend.transportation
     *
     * @return the value of dbo.WM_SaleSend.transportation
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public String getTransportation() {
        return transportation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_SaleSend.transportation
     *
     * @param transportation the value for dbo.WM_SaleSend.transportation
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setTransportation(String transportation) {
        this.transportation = transportation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_SaleSend.billCode
     *
     * @return the value of dbo.WM_SaleSend.billCode
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public String getBillcode() {
        return billcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_SaleSend.billCode
     *
     * @param billcode the value for dbo.WM_SaleSend.billCode
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setBillcode(String billcode) {
        this.billcode = billcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_SaleSend.billState
     *
     * @return the value of dbo.WM_SaleSend.billState
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public String getBillstate() {
        return billstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_SaleSend.billState
     *
     * @param billstate the value for dbo.WM_SaleSend.billState
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setBillstate(String billstate) {
        this.billstate = billstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_SaleSend.billDate
     *
     * @return the value of dbo.WM_SaleSend.billDate
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public Date getBilldate() {
        return billdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_SaleSend.billDate
     *
     * @param billdate the value for dbo.WM_SaleSend.billDate
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setBilldate(Date billdate) {
        this.billdate = billdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_SaleSend.recordPersonUid
     *
     * @return the value of dbo.WM_SaleSend.recordPersonUid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public String getRecordpersonuid() {
        return recordpersonuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_SaleSend.recordPersonUid
     *
     * @param recordpersonuid the value for dbo.WM_SaleSend.recordPersonUid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setRecordpersonuid(String recordpersonuid) {
        this.recordpersonuid = recordpersonuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_SaleSend.recordDate
     *
     * @return the value of dbo.WM_SaleSend.recordDate
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public Date getRecorddate() {
        return recorddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_SaleSend.recordDate
     *
     * @param recorddate the value for dbo.WM_SaleSend.recordDate
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setRecorddate(Date recorddate) {
        this.recorddate = recorddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_SaleSend.recordTime
     *
     * @return the value of dbo.WM_SaleSend.recordTime
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public Date getRecordtime() {
        return recordtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_SaleSend.recordTime
     *
     * @param recordtime the value for dbo.WM_SaleSend.recordTime
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setRecordtime(Date recordtime) {
        this.recordtime = recordtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_SaleSend.auditPersonUid
     *
     * @return the value of dbo.WM_SaleSend.auditPersonUid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public String getAuditpersonuid() {
        return auditpersonuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_SaleSend.auditPersonUid
     *
     * @param auditpersonuid the value for dbo.WM_SaleSend.auditPersonUid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setAuditpersonuid(String auditpersonuid) {
        this.auditpersonuid = auditpersonuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_SaleSend.auditDate
     *
     * @return the value of dbo.WM_SaleSend.auditDate
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public Date getAuditdate() {
        return auditdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_SaleSend.auditDate
     *
     * @param auditdate the value for dbo.WM_SaleSend.auditDate
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setAuditdate(Date auditdate) {
        this.auditdate = auditdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_SaleSend.auditTime
     *
     * @return the value of dbo.WM_SaleSend.auditTime
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public Date getAudittime() {
        return audittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_SaleSend.auditTime
     *
     * @param audittime the value for dbo.WM_SaleSend.auditTime
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setAudittime(Date audittime) {
        this.audittime = audittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_SaleSend.barCode
     *
     * @return the value of dbo.WM_SaleSend.barCode
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public String getBarcode() {
        return barcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_SaleSend.barCode
     *
     * @param barcode the value for dbo.WM_SaleSend.barCode
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setBarcode(String barcode) {
        this.barcode = barcode;
    }






    public Integer getIsreturn() {
		return isreturn;
	}

	public void setIsreturn(Integer isreturn) {
		this.isreturn = isreturn;
	}

    public String getTransport() {
        return transport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_SaleSend.transport
     *
     * @param transport the value for dbo.WM_SaleSend.transport
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setTransport(String transport) {
        this.transport = transport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_SaleSend.sobGid
     *
     * @return the value of dbo.WM_SaleSend.sobGid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public String getSobgid() {
        return sobgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_SaleSend.sobGid
     *
     * @param sobgid the value for dbo.WM_SaleSend.sobGid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setSobgid(String sobgid) {
        this.sobgid = sobgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_SaleSend.orgGid
     *
     * @return the value of dbo.WM_SaleSend.orgGid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public String getOrggid() {
        return orggid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_SaleSend.orgGid
     *
     * @param orggid the value for dbo.WM_SaleSend.orgGid
     *
     * @mbggenerated Wed Dec 02 15:26:30 CST 2015
     */
    public void setOrggid(String orggid) {
        this.orggid = orggid;
    }

	public Integer getIsdel() {
		return isdel;
	}

	public void setIsdel(Integer isdel) {
		this.isdel = isdel;
	}

    
}