package com.emi.wms.bean;

import java.io.Serializable;
import java.util.Date;

import com.emi.sys.core.annotation.EmiColumn;
import com.emi.sys.core.annotation.EmiTable;
@EmiTable(name="WM_SaleOut")
public class WmSaleout implements Serializable {
	private static final long serialVersionUID = -3151893624576948785L;

	//pk 
	@EmiColumn(name="pk" ,increment=true)
    private Integer pk;

	//gid 
	@EmiColumn(name="gid" ,ID=true)
    private String gid;

	//备注
	@EmiColumn(name="notes" )
    private String notes;

	//单据类型 
	@EmiColumn(name="documenttypeuid" )
    private String documenttypeuid;

	//业务类型 
	@EmiColumn(name="businesstypeuid" )
    private String businesstypeuid;

	//仓库uid 
	@EmiColumn(name="whuid" )
    private String whuid;

	//部门uid
	@EmiColumn(name="departmentuid" )
    private String departmentuid;

	//业务员uid 
	@EmiColumn(name="personuid" )
    private String personuid;

	//客户uid
	@EmiColumn(name="customeruid" )
    private String customeruid;

	//单据号 
	@EmiColumn(name="billcode" )
    private String billcode;

	//单据状态 
	@EmiColumn(name="billstate" )
    private String billstate;

	//单据日期 
	@EmiColumn(name="billdate" )
    private Date billdate;

	//录入人 
	@EmiColumn(name="recordperson" )
    private String recordperson;

	//录入日期 
	@EmiColumn(name="recorddate" )
    private Date recorddate;

	//录入时间
	@EmiColumn(name="recordtime" )
    private Date recordtime;

	//审核人
	@EmiColumn(name="auditperson" )
    private String auditperson;

	//审核日期 
	@EmiColumn(name="auditdate" )
    private Date auditdate;

	//审核时间
	@EmiColumn(name="audittime" )
    private Date audittime;

	//条码
	@EmiColumn(name="barcode" )
    private String barcode;

	//红蓝单据识别 
	@EmiColumn(name="isreturn" )
    private Integer isreturn;

	//组织id
	@EmiColumn(name="orggid" )
    private String orggid;

	//帐套id
	@EmiColumn(name="sobgid" )
    private String sobgid;

	//是否记账
	@EmiColumn(name="accounting" )
    private Integer accounting;

	//是否锁定
	@EmiColumn(name="lock" )
    private Integer lock;

	@EmiColumn(name="badge" )
    private Integer badge;
	
	private String recordPersonName;
	private String departName;
	private String wareHouseName;
	private String customerName;
	private String goodsUid;
	private String goodsCode;
	
	
    public String getCustomerName() {
		return customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	public String getRecordPersonName() {
		return recordPersonName;
	}

	public void setRecordPersonName(String recordPersonName) {
		this.recordPersonName = recordPersonName;
	}

	public String getDepartName() {
		return departName;
	}

	public void setDepartName(String departName) {
		this.departName = departName;
	}

	public String getWareHouseName() {
		return wareHouseName;
	}

	public void setWareHouseName(String wareHouseName) {
		this.wareHouseName = wareHouseName;
	}

	public Integer getBadge() {
		return badge;
	}

	public void setBadge(Integer badge) {
		this.badge = badge;
	}

	public Integer getPk() {
        return pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_SaleOut.pk
     *
     * @param pk the value for dbo.WM_SaleOut.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setPk(Integer pk) {
        this.pk = pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_SaleOut.gid
     *
     * @return the value of dbo.WM_SaleOut.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_SaleOut.gid
     *
     * @param gid the value for dbo.WM_SaleOut.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setGid(String gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_SaleOut.notes
     *
     * @return the value of dbo.WM_SaleOut.notes
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_SaleOut.notes
     *
     * @param notes the value for dbo.WM_SaleOut.notes
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setNotes(String notes) {
        this.notes = notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_SaleOut.documentTypeUid
     *
     * @return the value of dbo.WM_SaleOut.documentTypeUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getDocumenttypeuid() {
        return documenttypeuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_SaleOut.documentTypeUid
     *
     * @param documenttypeuid the value for dbo.WM_SaleOut.documentTypeUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setDocumenttypeuid(String documenttypeuid) {
        this.documenttypeuid = documenttypeuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_SaleOut.businessTypeUid
     *
     * @return the value of dbo.WM_SaleOut.businessTypeUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getBusinesstypeuid() {
        return businesstypeuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_SaleOut.businessTypeUid
     *
     * @param businesstypeuid the value for dbo.WM_SaleOut.businessTypeUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setBusinesstypeuid(String businesstypeuid) {
        this.businesstypeuid = businesstypeuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_SaleOut.whUid
     *
     * @return the value of dbo.WM_SaleOut.whUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getWhuid() {
        return whuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_SaleOut.whUid
     *
     * @param whuid the value for dbo.WM_SaleOut.whUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setWhuid(String whuid) {
        this.whuid = whuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_SaleOut.departmentUid
     *
     * @return the value of dbo.WM_SaleOut.departmentUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getDepartmentuid() {
        return departmentuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_SaleOut.departmentUid
     *
     * @param departmentuid the value for dbo.WM_SaleOut.departmentUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setDepartmentuid(String departmentuid) {
        this.departmentuid = departmentuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_SaleOut.personUid
     *
     * @return the value of dbo.WM_SaleOut.personUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getPersonuid() {
        return personuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_SaleOut.personUid
     *
     * @param personuid the value for dbo.WM_SaleOut.personUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setPersonuid(String personuid) {
        this.personuid = personuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_SaleOut.customerUid
     *
     * @return the value of dbo.WM_SaleOut.customerUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getCustomeruid() {
        return customeruid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_SaleOut.customerUid
     *
     * @param customeruid the value for dbo.WM_SaleOut.customerUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setCustomeruid(String customeruid) {
        this.customeruid = customeruid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_SaleOut.billCode
     *
     * @return the value of dbo.WM_SaleOut.billCode
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getBillcode() {
        return billcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_SaleOut.billCode
     *
     * @param billcode the value for dbo.WM_SaleOut.billCode
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setBillcode(String billcode) {
        this.billcode = billcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_SaleOut.billState
     *
     * @return the value of dbo.WM_SaleOut.billState
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getBillstate() {
        return billstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_SaleOut.billState
     *
     * @param billstate the value for dbo.WM_SaleOut.billState
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setBillstate(String billstate) {
        this.billstate = billstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_SaleOut.billDate
     *
     * @return the value of dbo.WM_SaleOut.billDate
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Date getBilldate() {
        return billdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_SaleOut.billDate
     *
     * @param billdate the value for dbo.WM_SaleOut.billDate
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setBilldate(Date billdate) {
        this.billdate = billdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_SaleOut.recordPerson
     *
     * @return the value of dbo.WM_SaleOut.recordPerson
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getRecordperson() {
        return recordperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_SaleOut.recordPerson
     *
     * @param recordperson the value for dbo.WM_SaleOut.recordPerson
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setRecordperson(String recordperson) {
        this.recordperson = recordperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_SaleOut.recordDate
     *
     * @return the value of dbo.WM_SaleOut.recordDate
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Date getRecorddate() {
        return recorddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_SaleOut.recordDate
     *
     * @param recorddate the value for dbo.WM_SaleOut.recordDate
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setRecorddate(Date recorddate) {
        this.recorddate = recorddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_SaleOut.recordTime
     *
     * @return the value of dbo.WM_SaleOut.recordTime
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Date getRecordtime() {
        return recordtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_SaleOut.recordTime
     *
     * @param recordtime the value for dbo.WM_SaleOut.recordTime
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setRecordtime(Date recordtime) {
        this.recordtime = recordtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_SaleOut.auditPerson
     *
     * @return the value of dbo.WM_SaleOut.auditPerson
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getAuditperson() {
        return auditperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_SaleOut.auditPerson
     *
     * @param auditperson the value for dbo.WM_SaleOut.auditPerson
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setAuditperson(String auditperson) {
        this.auditperson = auditperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_SaleOut.auditDate
     *
     * @return the value of dbo.WM_SaleOut.auditDate
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Date getAuditdate() {
        return auditdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_SaleOut.auditDate
     *
     * @param auditdate the value for dbo.WM_SaleOut.auditDate
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setAuditdate(Date auditdate) {
        this.auditdate = auditdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_SaleOut.auditTime
     *
     * @return the value of dbo.WM_SaleOut.auditTime
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Date getAudittime() {
        return audittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_SaleOut.auditTime
     *
     * @param audittime the value for dbo.WM_SaleOut.auditTime
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setAudittime(Date audittime) {
        this.audittime = audittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_SaleOut.barCode
     *
     * @return the value of dbo.WM_SaleOut.barCode
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getBarcode() {
        return barcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_SaleOut.barCode
     *
     * @param barcode the value for dbo.WM_SaleOut.barCode
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setBarcode(String barcode) {
        this.barcode = barcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_SaleOut.isReturn
     *
     * @return the value of dbo.WM_SaleOut.isReturn
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Integer getIsreturn() {
        return isreturn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_SaleOut.isReturn
     *
     * @param isreturn the value for dbo.WM_SaleOut.isReturn
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setIsreturn(Integer isreturn) {
        this.isreturn = isreturn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_SaleOut.orgGid
     *
     * @return the value of dbo.WM_SaleOut.orgGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getOrggid() {
        return orggid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_SaleOut.orgGid
     *
     * @param orggid the value for dbo.WM_SaleOut.orgGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setOrggid(String orggid) {
        this.orggid = orggid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_SaleOut.sobGid
     *
     * @return the value of dbo.WM_SaleOut.sobGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getSobgid() {
        return sobgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_SaleOut.sobGid
     *
     * @param sobgid the value for dbo.WM_SaleOut.sobGid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setSobgid(String sobgid) {
        this.sobgid = sobgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_SaleOut.accounting
     *
     * @return the value of dbo.WM_SaleOut.accounting
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Integer getAccounting() {
        return accounting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_SaleOut.accounting
     *
     * @param accounting the value for dbo.WM_SaleOut.accounting
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setAccounting(Integer accounting) {
        this.accounting = accounting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_SaleOut.lock
     *
     * @return the value of dbo.WM_SaleOut.lock
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Integer getLock() {
        return lock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_SaleOut.lock
     *
     * @param lock the value for dbo.WM_SaleOut.lock
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setLock(Integer lock) {
        this.lock = lock;
    }

	public String getGoodsUid() {
		return goodsUid;
	}

	public void setGoodsUid(String goodsUid) {
		this.goodsUid = goodsUid;
	}

	public String getGoodsCode() {
		return goodsCode;
	}
	
	public void setGoodsCode(String goodsCode) {
		this.goodsCode = goodsCode;
	}
    
    
}