package com.emi.wms.bean;

public class WmTaskorder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_TaskOrder.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Integer pk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_TaskOrder.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String gid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_TaskOrder.notes
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String notes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_TaskOrder.taskCuid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String taskcuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_TaskOrder.billTypeUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String billtypeuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_TaskOrder.billCode
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String billcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WM_TaskOrder.billUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String billuid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_TaskOrder.pk
     *
     * @return the value of dbo.WM_TaskOrder.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Integer getPk() {
        return pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_TaskOrder.pk
     *
     * @param pk the value for dbo.WM_TaskOrder.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setPk(Integer pk) {
        this.pk = pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_TaskOrder.gid
     *
     * @return the value of dbo.WM_TaskOrder.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_TaskOrder.gid
     *
     * @param gid the value for dbo.WM_TaskOrder.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setGid(String gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_TaskOrder.notes
     *
     * @return the value of dbo.WM_TaskOrder.notes
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_TaskOrder.notes
     *
     * @param notes the value for dbo.WM_TaskOrder.notes
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setNotes(String notes) {
        this.notes = notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_TaskOrder.taskCuid
     *
     * @return the value of dbo.WM_TaskOrder.taskCuid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getTaskcuid() {
        return taskcuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_TaskOrder.taskCuid
     *
     * @param taskcuid the value for dbo.WM_TaskOrder.taskCuid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setTaskcuid(String taskcuid) {
        this.taskcuid = taskcuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_TaskOrder.billTypeUid
     *
     * @return the value of dbo.WM_TaskOrder.billTypeUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getBilltypeuid() {
        return billtypeuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_TaskOrder.billTypeUid
     *
     * @param billtypeuid the value for dbo.WM_TaskOrder.billTypeUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setBilltypeuid(String billtypeuid) {
        this.billtypeuid = billtypeuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_TaskOrder.billCode
     *
     * @return the value of dbo.WM_TaskOrder.billCode
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getBillcode() {
        return billcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_TaskOrder.billCode
     *
     * @param billcode the value for dbo.WM_TaskOrder.billCode
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setBillcode(String billcode) {
        this.billcode = billcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WM_TaskOrder.billUid
     *
     * @return the value of dbo.WM_TaskOrder.billUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getBilluid() {
        return billuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WM_TaskOrder.billUid
     *
     * @param billuid the value for dbo.WM_TaskOrder.billUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setBilluid(String billuid) {
        this.billuid = billuid;
    }
}