package com.emi.wms.bean;

import java.util.Date;

public class YmPermission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.YM_Permission.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Integer pk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.YM_Permission.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String gid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.YM_Permission.perCode
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String percode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.YM_Permission.perName
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String pername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.YM_Permission.parentUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String parentuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.YM_Permission.parentCode
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String parentcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.YM_Permission.last
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Boolean last;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.YM_Permission.layer
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Integer layer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.YM_Permission.sonSysId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String sonsysid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.YM_Permission.beginTimes
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Date begintimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.YM_Permission.endTimes
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Date endtimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.YM_Permission.sobId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String sobid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.YM_Permission.orgId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String orgid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.YM_Permission.pk
     *
     * @return the value of dbo.YM_Permission.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Integer getPk() {
        return pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.YM_Permission.pk
     *
     * @param pk the value for dbo.YM_Permission.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setPk(Integer pk) {
        this.pk = pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.YM_Permission.gid
     *
     * @return the value of dbo.YM_Permission.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.YM_Permission.gid
     *
     * @param gid the value for dbo.YM_Permission.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setGid(String gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.YM_Permission.perCode
     *
     * @return the value of dbo.YM_Permission.perCode
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getPercode() {
        return percode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.YM_Permission.perCode
     *
     * @param percode the value for dbo.YM_Permission.perCode
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setPercode(String percode) {
        this.percode = percode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.YM_Permission.perName
     *
     * @return the value of dbo.YM_Permission.perName
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getPername() {
        return pername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.YM_Permission.perName
     *
     * @param pername the value for dbo.YM_Permission.perName
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setPername(String pername) {
        this.pername = pername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.YM_Permission.parentUid
     *
     * @return the value of dbo.YM_Permission.parentUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getParentuid() {
        return parentuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.YM_Permission.parentUid
     *
     * @param parentuid the value for dbo.YM_Permission.parentUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setParentuid(String parentuid) {
        this.parentuid = parentuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.YM_Permission.parentCode
     *
     * @return the value of dbo.YM_Permission.parentCode
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getParentcode() {
        return parentcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.YM_Permission.parentCode
     *
     * @param parentcode the value for dbo.YM_Permission.parentCode
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setParentcode(String parentcode) {
        this.parentcode = parentcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.YM_Permission.last
     *
     * @return the value of dbo.YM_Permission.last
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Boolean getLast() {
        return last;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.YM_Permission.last
     *
     * @param last the value for dbo.YM_Permission.last
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setLast(Boolean last) {
        this.last = last;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.YM_Permission.layer
     *
     * @return the value of dbo.YM_Permission.layer
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Integer getLayer() {
        return layer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.YM_Permission.layer
     *
     * @param layer the value for dbo.YM_Permission.layer
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setLayer(Integer layer) {
        this.layer = layer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.YM_Permission.sonSysId
     *
     * @return the value of dbo.YM_Permission.sonSysId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getSonsysid() {
        return sonsysid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.YM_Permission.sonSysId
     *
     * @param sonsysid the value for dbo.YM_Permission.sonSysId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setSonsysid(String sonsysid) {
        this.sonsysid = sonsysid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.YM_Permission.beginTimes
     *
     * @return the value of dbo.YM_Permission.beginTimes
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Date getBegintimes() {
        return begintimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.YM_Permission.beginTimes
     *
     * @param begintimes the value for dbo.YM_Permission.beginTimes
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setBegintimes(Date begintimes) {
        this.begintimes = begintimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.YM_Permission.endTimes
     *
     * @return the value of dbo.YM_Permission.endTimes
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Date getEndtimes() {
        return endtimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.YM_Permission.endTimes
     *
     * @param endtimes the value for dbo.YM_Permission.endTimes
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setEndtimes(Date endtimes) {
        this.endtimes = endtimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.YM_Permission.sobId
     *
     * @return the value of dbo.YM_Permission.sobId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getSobid() {
        return sobid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.YM_Permission.sobId
     *
     * @param sobid the value for dbo.YM_Permission.sobId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setSobid(String sobid) {
        this.sobid = sobid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.YM_Permission.orgId
     *
     * @return the value of dbo.YM_Permission.orgId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getOrgid() {
        return orgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.YM_Permission.orgId
     *
     * @param orgid the value for dbo.YM_Permission.orgId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setOrgid(String orgid) {
        this.orgid = orgid;
    }
}