package com.emi.wms.bean;

import java.util.Date;

public class YmRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.YM_Role.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Integer pk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.YM_Role.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String gid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.YM_Role.roleCode
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String rolecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.YM_Role.cRroleName
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String crrolename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.YM_Role.cNotes
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String cnotes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.YM_Role.dBeginTimes
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Date dbegintimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.YM_Role.dEndTimes
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Date dendtimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.YM_Role.sfbId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String sfbid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.YM_Role.orgId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String orgid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.YM_Role.pk
     *
     * @return the value of dbo.YM_Role.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Integer getPk() {
        return pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.YM_Role.pk
     *
     * @param pk the value for dbo.YM_Role.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setPk(Integer pk) {
        this.pk = pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.YM_Role.gid
     *
     * @return the value of dbo.YM_Role.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.YM_Role.gid
     *
     * @param gid the value for dbo.YM_Role.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setGid(String gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.YM_Role.roleCode
     *
     * @return the value of dbo.YM_Role.roleCode
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getRolecode() {
        return rolecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.YM_Role.roleCode
     *
     * @param rolecode the value for dbo.YM_Role.roleCode
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setRolecode(String rolecode) {
        this.rolecode = rolecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.YM_Role.cRroleName
     *
     * @return the value of dbo.YM_Role.cRroleName
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getCrrolename() {
        return crrolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.YM_Role.cRroleName
     *
     * @param crrolename the value for dbo.YM_Role.cRroleName
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setCrrolename(String crrolename) {
        this.crrolename = crrolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.YM_Role.cNotes
     *
     * @return the value of dbo.YM_Role.cNotes
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getCnotes() {
        return cnotes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.YM_Role.cNotes
     *
     * @param cnotes the value for dbo.YM_Role.cNotes
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setCnotes(String cnotes) {
        this.cnotes = cnotes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.YM_Role.dBeginTimes
     *
     * @return the value of dbo.YM_Role.dBeginTimes
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Date getDbegintimes() {
        return dbegintimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.YM_Role.dBeginTimes
     *
     * @param dbegintimes the value for dbo.YM_Role.dBeginTimes
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setDbegintimes(Date dbegintimes) {
        this.dbegintimes = dbegintimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.YM_Role.dEndTimes
     *
     * @return the value of dbo.YM_Role.dEndTimes
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Date getDendtimes() {
        return dendtimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.YM_Role.dEndTimes
     *
     * @param dendtimes the value for dbo.YM_Role.dEndTimes
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setDendtimes(Date dendtimes) {
        this.dendtimes = dendtimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.YM_Role.sfbId
     *
     * @return the value of dbo.YM_Role.sfbId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getSfbid() {
        return sfbid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.YM_Role.sfbId
     *
     * @param sfbid the value for dbo.YM_Role.sfbId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setSfbid(String sfbid) {
        this.sfbid = sfbid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.YM_Role.orgId
     *
     * @return the value of dbo.YM_Role.orgId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getOrgid() {
        return orgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.YM_Role.orgId
     *
     * @param orgid the value for dbo.YM_Role.orgId
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setOrgid(String orgid) {
        this.orgid = orgid;
    }
}