package com.emi.wms.bean;

import java.util.Date;

public class YmUserrole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.YM_UserRole.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Integer pk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.YM_UserRole.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String gid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.YM_UserRole.userUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String useruid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.YM_UserRole.roleUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String roleuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.YM_UserRole.notes
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private String notes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.YM_UserRole.beginTimes
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Date begintimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.YM_UserRole.endTimes
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    private Date endtimes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.YM_UserRole.pk
     *
     * @return the value of dbo.YM_UserRole.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Integer getPk() {
        return pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.YM_UserRole.pk
     *
     * @param pk the value for dbo.YM_UserRole.pk
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setPk(Integer pk) {
        this.pk = pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.YM_UserRole.gid
     *
     * @return the value of dbo.YM_UserRole.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.YM_UserRole.gid
     *
     * @param gid the value for dbo.YM_UserRole.gid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setGid(String gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.YM_UserRole.userUid
     *
     * @return the value of dbo.YM_UserRole.userUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getUseruid() {
        return useruid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.YM_UserRole.userUid
     *
     * @param useruid the value for dbo.YM_UserRole.userUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setUseruid(String useruid) {
        this.useruid = useruid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.YM_UserRole.roleUid
     *
     * @return the value of dbo.YM_UserRole.roleUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getRoleuid() {
        return roleuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.YM_UserRole.roleUid
     *
     * @param roleuid the value for dbo.YM_UserRole.roleUid
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setRoleuid(String roleuid) {
        this.roleuid = roleuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.YM_UserRole.notes
     *
     * @return the value of dbo.YM_UserRole.notes
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.YM_UserRole.notes
     *
     * @param notes the value for dbo.YM_UserRole.notes
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setNotes(String notes) {
        this.notes = notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.YM_UserRole.beginTimes
     *
     * @return the value of dbo.YM_UserRole.beginTimes
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Date getBegintimes() {
        return begintimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.YM_UserRole.beginTimes
     *
     * @param begintimes the value for dbo.YM_UserRole.beginTimes
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setBegintimes(Date begintimes) {
        this.begintimes = begintimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.YM_UserRole.endTimes
     *
     * @return the value of dbo.YM_UserRole.endTimes
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public Date getEndtimes() {
        return endtimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.YM_UserRole.endTimes
     *
     * @param endtimes the value for dbo.YM_UserRole.endTimes
     *
     * @mbggenerated Wed Dec 02 15:26:31 CST 2015
     */
    public void setEndtimes(Date endtimes) {
        this.endtimes = endtimes;
    }
}